// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActivityUnread = `-- name: CountActivityUnread :one
SELECT count(*)
FROM activity_visible_events v
LEFT JOIN activity_event_reads r ON r.event_id = v.id AND r.user_id = v.reader_id
WHERE v.reader_id = $1
  AND r.event_id IS NULL
`

// The badge is exactly "visible events with no read row for me" — the same
// view, the same anti-join, as the read_by_me column above.
func (q *Queries) CountActivityUnread(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActivityUnread, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActivityEventById = `-- name: GetActivityEventById :one
SELECT e.id, e.seq, e.group_id, e.actor_id, e.actor_name, e.kind, e.title_id,
       e.title_name, e.payload, e.created_at, g.name AS group_name,
       FALSE AS read_by_me
FROM activity_events e
JOIN groups g ON g.id = e.group_id
WHERE e.id = $1
`

type GetActivityEventByIdRow struct {
	ID        string
	Seq       int64
	GroupID   string
	ActorID   string
	ActorName string
	Kind      string
	TitleID   pgtype.Text
	TitleName pgtype.Text
	Payload   []byte
	CreatedAt pgtype.Timestamptz
	GroupName string
	ReadByMe  bool
}

// Used by the LISTEN loop to turn a notified id into the row it pushes. No
// visibility predicate here: the loop has no reader, and the hub filters per
// subscriber.
//
// read_by_me is FALSE for the same reason: a pushed event was just written, so
// it is unread for every subscriber it reaches. The column is selected rather
// than omitted so this row stays field-for-field identical to
// GetActivityFeedRows' — the store converts directly between the two.
func (q *Queries) GetActivityEventById(ctx context.Context, id string) (GetActivityEventByIdRow, error) {
	row := q.db.QueryRow(ctx, getActivityEventById, id)
	var i GetActivityEventByIdRow
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.GroupID,
		&i.ActorID,
		&i.ActorName,
		&i.Kind,
		&i.TitleID,
		&i.TitleName,
		&i.Payload,
		&i.CreatedAt,
		&i.GroupName,
		&i.ReadByMe,
	)
	return i, err
}

const getActivityFeedRows = `-- name: GetActivityFeedRows :many
SELECT v.id, v.seq, v.group_id, v.actor_id, v.actor_name, v.kind, v.title_id,
       v.title_name, v.payload, v.created_at, v.group_name,
       (r.event_id IS NOT NULL)::boolean AS read_by_me
FROM activity_visible_events v
LEFT JOIN activity_event_reads r ON r.event_id = v.id AND r.user_id = v.reader_id
WHERE v.reader_id = $1
  AND ($2::bigint IS NULL OR v.seq < $2::bigint)
ORDER BY v.seq DESC
LIMIT $3::bigint
`

type GetActivityFeedRowsParams struct {
	UserID   string
	Before   pgtype.Int8
	RowLimit int64
}

type GetActivityFeedRowsRow struct {
	ID        string
	Seq       int64
	GroupID   string
	ActorID   string
	ActorName string
	Kind      string
	TitleID   pgtype.Text
	TitleName pgtype.Text
	Payload   []byte
	CreatedAt pgtype.Timestamptz
	GroupName string
	ReadByMe  bool
}

// Visibility comes from activity_visible_events (your groups, never your own
// actions, nothing from a deleted group), so this query and the badge cannot
// drift apart. Membership is part of that view, so leaving a group hides its
// history immediately.
//
// read_by_me is the reader's own state, joined per row: the same event is read
// for one member and unread for another, which is why it cannot live on
// activity_events.
func (q *Queries) GetActivityFeedRows(ctx context.Context, arg GetActivityFeedRowsParams) ([]GetActivityFeedRowsRow, error) {
	rows, err := q.db.Query(ctx, getActivityFeedRows, arg.UserID, arg.Before, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActivityFeedRowsRow
	for rows.Next() {
		var i GetActivityFeedRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.GroupID,
			&i.ActorID,
			&i.ActorName,
			&i.Kind,
			&i.TitleID,
			&i.TitleName,
			&i.Payload,
			&i.CreatedAt,
			&i.GroupName,
			&i.ReadByMe,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertActivityEventRow = `-- name: InsertActivityEventRow :one
INSERT INTO activity_events (
    id, group_id, actor_id, actor_name, kind, title_id, title_name, payload, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, seq, group_id, actor_id, actor_name, kind, title_id, title_name, payload, created_at
`

type InsertActivityEventRowParams struct {
	ID        string
	GroupID   string
	ActorID   string
	ActorName string
	Kind      string
	TitleID   pgtype.Text
	TitleName pgtype.Text
	Payload   []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertActivityEventRow(ctx context.Context, arg InsertActivityEventRowParams) (ActivityEvent, error) {
	row := q.db.QueryRow(ctx, insertActivityEventRow,
		arg.ID,
		arg.GroupID,
		arg.ActorID,
		arg.ActorName,
		arg.Kind,
		arg.TitleID,
		arg.TitleName,
		arg.Payload,
		arg.CreatedAt,
	)
	var i ActivityEvent
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.GroupID,
		&i.ActorID,
		&i.ActorName,
		&i.Kind,
		&i.TitleID,
		&i.TitleName,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const markActivityEventRead = `-- name: MarkActivityEventRead :one
INSERT INTO activity_event_reads (user_id, event_id, read_at)
SELECT v.reader_id, v.id, $1::timestamptz
FROM activity_visible_events v
WHERE v.reader_id = $2
  AND v.id = $3
ON CONFLICT (user_id, event_id) DO UPDATE
SET read_at = activity_event_reads.read_at
RETURNING event_id
`

type MarkActivityEventReadParams struct {
	ReadAt  pgtype.Timestamptz
	UserID  string
	EventID string
}

// Marks one event read for one reader, and answers whether that event was
// visible to them at all: the INSERT's source is the visibility view, so a
// non-member (or an unknown id) selects no row and the statement returns
// nothing, which the store turns into ErrRecordNotFound.
//
// ON CONFLICT ... DO UPDATE, rather than DO NOTHING, is what makes the two
// outcomes distinguishable while staying idempotent: DO NOTHING also returns no
// row for an event already read, which is a success. The update assigns read_at
// to itself, so a second click keeps the moment of the first read and only ever
// costs a rewritten row version.
func (q *Queries) MarkActivityEventRead(ctx context.Context, arg MarkActivityEventReadParams) (string, error) {
	row := q.db.QueryRow(ctx, markActivityEventRead, arg.ReadAt, arg.UserID, arg.EventID)
	var event_id string
	err := row.Scan(&event_id)
	return event_id, err
}

const markAllActivityEventsRead = `-- name: MarkAllActivityEventsRead :exec
INSERT INTO activity_event_reads (user_id, event_id, read_at)
SELECT v.reader_id, v.id, $1::timestamptz
FROM activity_visible_events v
WHERE v.reader_id = $2
ON CONFLICT (user_id, event_id) DO NOTHING
`

type MarkAllActivityEventsReadParams struct {
	ReadAt pgtype.Timestamptz
	UserID string
}

// One statement, not one round trip per event: with read state stored per event
// there is no watermark to move, so clearing the badge means writing a row for
// every event the reader can currently see. DO NOTHING keeps it idempotent and
// keeps the original read_at of anything already read.
func (q *Queries) MarkAllActivityEventsRead(ctx context.Context, arg MarkAllActivityEventsReadParams) error {
	_, err := q.db.Exec(ctx, markAllActivityEventsRead, arg.ReadAt, arg.UserID)
	return err
}

const notifyActivityEvent = `-- name: NotifyActivityEvent :exec
SELECT pg_notify('activity_events', $1::text)
`

// Fired inside the insert's transaction, so it is delivered only if that commit
// succeeds. The payload is the event id, not the row: pg_notify caps payloads at
// 8000 bytes, and the listener reads the row once and fans it out.
func (q *Queries) NotifyActivityEvent(ctx context.Context, eventID string) error {
	_, err := q.db.Exec(ctx, notifyActivityEvent, eventID)
	return err
}
