// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActivityUnread = `-- name: CountActivityUnread :one
SELECT count(*)
FROM activity_events e
JOIN group_members m ON m.group_id = e.group_id AND m.user_id = $1
JOIN groups g ON g.id = e.group_id AND NOT g.deleted
LEFT JOIN activity_reads r ON r.user_id = $1
WHERE e.actor_id <> $1
  AND e.seq > COALESCE(r.read_seq, 0)
`

func (q *Queries) CountActivityUnread(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActivityUnread, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActivityFeedRows = `-- name: GetActivityFeedRows :many
SELECT e.id, e.seq, e.group_id, e.actor_id, e.actor_name, e.kind, e.title_id, e.title_name, e.payload, e.created_at, g.name AS group_name
FROM activity_events e
JOIN group_members m ON m.group_id = e.group_id AND m.user_id = $1
JOIN groups g ON g.id = e.group_id AND NOT g.deleted
WHERE e.actor_id <> $1
  AND ($2::bigint IS NULL OR e.seq < $2::bigint)
ORDER BY e.seq DESC
LIMIT $3::bigint
`

type GetActivityFeedRowsParams struct {
	UserID   string
	Before   pgtype.Int8
	RowLimit int64
}

type GetActivityFeedRowsRow struct {
	ID        string
	Seq       int64
	GroupID   string
	ActorID   string
	ActorName string
	Kind      string
	TitleID   pgtype.Text
	TitleName pgtype.Text
	Payload   []byte
	CreatedAt pgtype.Timestamptz
	GroupName string
}

// The reader's own actions are excluded: they are recorded so everyone else is
// notified, not so the actor is notified about themselves. Membership is joined
// at read time, so leaving a group hides its history immediately.
func (q *Queries) GetActivityFeedRows(ctx context.Context, arg GetActivityFeedRowsParams) ([]GetActivityFeedRowsRow, error) {
	rows, err := q.db.Query(ctx, getActivityFeedRows, arg.UserID, arg.Before, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActivityFeedRowsRow
	for rows.Next() {
		var i GetActivityFeedRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Seq,
			&i.GroupID,
			&i.ActorID,
			&i.ActorName,
			&i.Kind,
			&i.TitleID,
			&i.TitleName,
			&i.Payload,
			&i.CreatedAt,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertActivityEventRow = `-- name: InsertActivityEventRow :one
INSERT INTO activity_events (
    id, group_id, actor_id, actor_name, kind, title_id, title_name, payload, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, seq, group_id, actor_id, actor_name, kind, title_id, title_name, payload, created_at
`

type InsertActivityEventRowParams struct {
	ID        string
	GroupID   string
	ActorID   string
	ActorName string
	Kind      string
	TitleID   pgtype.Text
	TitleName pgtype.Text
	Payload   []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertActivityEventRow(ctx context.Context, arg InsertActivityEventRowParams) (ActivityEvent, error) {
	row := q.db.QueryRow(ctx, insertActivityEventRow,
		arg.ID,
		arg.GroupID,
		arg.ActorID,
		arg.ActorName,
		arg.Kind,
		arg.TitleID,
		arg.TitleName,
		arg.Payload,
		arg.CreatedAt,
	)
	var i ActivityEvent
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.GroupID,
		&i.ActorID,
		&i.ActorName,
		&i.Kind,
		&i.TitleID,
		&i.TitleName,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const upsertActivityRead = `-- name: UpsertActivityRead :exec
INSERT INTO activity_reads (user_id, read_at, read_seq)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
SET read_at = EXCLUDED.read_at,
    read_seq = GREATEST(activity_reads.read_seq, EXCLUDED.read_seq)
`

type UpsertActivityReadParams struct {
	UserID  string
	ReadAt  pgtype.Timestamptz
	ReadSeq int64
}

// GREATEST keeps the watermark monotonic: a late request carrying an older seq
// must not un-read events the user has already seen.
func (q *Queries) UpsertActivityRead(ctx context.Context, arg UpsertActivityReadParams) error {
	_, err := q.db.Exec(ctx, upsertActivityRead, arg.UserID, arg.ReadAt, arg.ReadSeq)
	return err
}
