// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCommentRow = `-- name: DeleteCommentRow :execrows
DELETE FROM comments WHERE id = $1 AND user_id = $2
`

type DeleteCommentRowParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteCommentRow(ctx context.Context, arg DeleteCommentRowParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCommentRow, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCommentSeasons = `-- name: DeleteCommentSeasons :exec
DELETE FROM comment_seasons WHERE comment_id = $1
`

func (q *Queries) DeleteCommentSeasons(ctx context.Context, commentID string) error {
	_, err := q.db.Exec(ctx, deleteCommentSeasons, commentID)
	return err
}

const getCommentRowById = `-- name: GetCommentRowById :one
SELECT id, title_id, user_id, comment, created_at, updated_at FROM comments WHERE id = $1 AND user_id = $2
`

type GetCommentRowByIdParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetCommentRowById(ctx context.Context, arg GetCommentRowByIdParams) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentRowById, arg.ID, arg.UserID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TitleID,
		&i.UserID,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommentRowsByTitleId = `-- name: GetCommentRowsByTitleId :many
SELECT id, title_id, user_id, comment, created_at, updated_at FROM comments WHERE title_id = $1 AND user_id = ANY($2::text[])
`

type GetCommentRowsByTitleIdParams struct {
	TitleID string
	Column2 []string
}

func (q *Queries) GetCommentRowsByTitleId(ctx context.Context, arg GetCommentRowsByTitleIdParams) ([]Comment, error) {
	rows, err := q.db.Query(ctx, getCommentRowsByTitleId, arg.TitleID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.TitleID,
			&i.UserID,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentSeasons = `-- name: GetCommentSeasons :many
SELECT comment_id, season, comment, added_at, updated_at FROM comment_seasons WHERE comment_id = $1
`

func (q *Queries) GetCommentSeasons(ctx context.Context, commentID string) ([]CommentSeason, error) {
	rows, err := q.db.Query(ctx, getCommentSeasons, commentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommentSeason
	for rows.Next() {
		var i CommentSeason
		if err := rows.Scan(
			&i.CommentID,
			&i.Season,
			&i.Comment,
			&i.AddedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentSeasonsByCommentIds = `-- name: GetCommentSeasonsByCommentIds :many
SELECT comment_id, season, comment, added_at, updated_at FROM comment_seasons WHERE comment_id = ANY($1::text[])
`

func (q *Queries) GetCommentSeasonsByCommentIds(ctx context.Context, dollar_1 []string) ([]CommentSeason, error) {
	rows, err := q.db.Query(ctx, getCommentSeasonsByCommentIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommentSeason
	for rows.Next() {
		var i CommentSeason
		if err := rows.Scan(
			&i.CommentID,
			&i.Season,
			&i.Comment,
			&i.AddedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserCommentRowByTitle = `-- name: GetUserCommentRowByTitle :one
SELECT id, title_id, user_id, comment, created_at, updated_at FROM comments WHERE title_id = $1 AND user_id = $2
`

type GetUserCommentRowByTitleParams struct {
	TitleID string
	UserID  string
}

func (q *Queries) GetUserCommentRowByTitle(ctx context.Context, arg GetUserCommentRowByTitleParams) (Comment, error) {
	row := q.db.QueryRow(ctx, getUserCommentRowByTitle, arg.TitleID, arg.UserID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TitleID,
		&i.UserID,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertComment = `-- name: InsertComment :one
INSERT INTO comments (
    id, title_id, user_id, comment, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, title_id, user_id, comment, created_at, updated_at
`

type InsertCommentParams struct {
	ID        string
	TitleID   string
	UserID    string
	Comment   pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, insertComment,
		arg.ID,
		arg.TitleID,
		arg.UserID,
		arg.Comment,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TitleID,
		&i.UserID,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCommentSeason = `-- name: InsertCommentSeason :exec
INSERT INTO comment_seasons (
    comment_id, season, comment, added_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5
)
`

type InsertCommentSeasonParams struct {
	CommentID string
	Season    string
	Comment   string
	AddedAt   pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) InsertCommentSeason(ctx context.Context, arg InsertCommentSeasonParams) error {
	_, err := q.db.Exec(ctx, insertCommentSeason,
		arg.CommentID,
		arg.Season,
		arg.Comment,
		arg.AddedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateCommentRow = `-- name: UpdateCommentRow :one
UPDATE comments
SET comment = $3, updated_at = $4
WHERE id = $1 AND user_id = $2
RETURNING id, title_id, user_id, comment, created_at, updated_at
`

type UpdateCommentRowParams struct {
	ID        string
	UserID    string
	Comment   pgtype.Text
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateCommentRow(ctx context.Context, arg UpdateCommentRowParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateCommentRow,
		arg.ID,
		arg.UserID,
		arg.Comment,
		arg.UpdatedAt,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TitleID,
		&i.UserID,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
