// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGroupTitle = `-- name: DeleteGroupTitle :execrows
DELETE FROM group_titles WHERE group_id = $1 AND title_id = $2
`

type DeleteGroupTitleParams struct {
	GroupID string
	TitleID string
}

func (q *Queries) DeleteGroupTitle(ctx context.Context, arg DeleteGroupTitleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGroupTitle, arg.GroupID, arg.TitleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGroupMemberIds = `-- name: GetGroupMemberIds :many
SELECT user_id FROM group_members WHERE group_id = $1 ORDER BY user_id
`

func (q *Queries) GetGroupMemberIds(ctx context.Context, groupID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getGroupMemberIds, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupMemberUsers = `-- name: GetGroupMemberUsers :many
SELECT u.id, u.name, u.email, u.username, u.password_hash, u.avatar_url, u.role, u.is_active, u.last_login_at, u.created_at, u.updated_at FROM group_members m
JOIN users u ON u.id = m.user_id
WHERE m.group_id = $1
ORDER BY u.id
`

func (q *Queries) GetGroupMemberUsers(ctx context.Context, groupID string) ([]User, error) {
	rows, err := q.db.Query(ctx, getGroupMemberUsers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.AvatarUrl,
			&i.Role,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupRow = `-- name: GetGroupRow :one
SELECT id, name, description, owner_id, deleted, deleted_at, created_at, updated_at FROM groups
WHERE id = $1 AND NOT deleted
  AND EXISTS (SELECT 1 FROM group_members WHERE group_id = $1 AND user_id = $2)
`

type GetGroupRowParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetGroupRow(ctx context.Context, arg GetGroupRowParams) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupRow, arg.ID, arg.UserID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupRowAnyById = `-- name: GetGroupRowAnyById :one
SELECT id, name, description, owner_id, deleted, deleted_at, created_at, updated_at FROM groups WHERE id = $1
`

// Migration-only verification read: fetches a group row by id regardless of
// deleted state or membership (the store's readers filter both out).
func (q *Queries) GetGroupRowAnyById(ctx context.Context, id string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupRowAnyById, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupTitleRow = `-- name: GetGroupTitleRow :one
SELECT group_id, title_id, title_type, watched, watched_at, added_at, updated_at FROM group_titles WHERE group_id = $1 AND title_id = $2
`

type GetGroupTitleRowParams struct {
	GroupID string
	TitleID string
}

func (q *Queries) GetGroupTitleRow(ctx context.Context, arg GetGroupTitleRowParams) (GroupTitle, error) {
	row := q.db.QueryRow(ctx, getGroupTitleRow, arg.GroupID, arg.TitleID)
	var i GroupTitle
	err := row.Scan(
		&i.GroupID,
		&i.TitleID,
		&i.TitleType,
		&i.Watched,
		&i.WatchedAt,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupTitleRows = `-- name: GetGroupTitleRows :many
SELECT group_id, title_id, title_type, watched, watched_at, added_at, updated_at FROM group_titles WHERE group_id = $1 ORDER BY title_id
`

func (q *Queries) GetGroupTitleRows(ctx context.Context, groupID string) ([]GroupTitle, error) {
	rows, err := q.db.Query(ctx, getGroupTitleRows, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupTitle
	for rows.Next() {
		var i GroupTitle
		if err := rows.Scan(
			&i.GroupID,
			&i.TitleID,
			&i.TitleType,
			&i.Watched,
			&i.WatchedAt,
			&i.AddedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupTitleSeasonRow = `-- name: GetGroupTitleSeasonRow :one
SELECT group_id, title_id, season, watched, watched_at, added_at, updated_at FROM group_title_seasons WHERE group_id = $1 AND title_id = $2 AND season = $3
`

type GetGroupTitleSeasonRowParams struct {
	GroupID string
	TitleID string
	Season  string
}

func (q *Queries) GetGroupTitleSeasonRow(ctx context.Context, arg GetGroupTitleSeasonRowParams) (GroupTitleSeason, error) {
	row := q.db.QueryRow(ctx, getGroupTitleSeasonRow, arg.GroupID, arg.TitleID, arg.Season)
	var i GroupTitleSeason
	err := row.Scan(
		&i.GroupID,
		&i.TitleID,
		&i.Season,
		&i.Watched,
		&i.WatchedAt,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupTitleSeasonRows = `-- name: GetGroupTitleSeasonRows :many
SELECT group_id, title_id, season, watched, watched_at, added_at, updated_at FROM group_title_seasons WHERE group_id = $1 ORDER BY title_id, season
`

func (q *Queries) GetGroupTitleSeasonRows(ctx context.Context, groupID string) ([]GroupTitleSeason, error) {
	rows, err := q.db.Query(ctx, getGroupTitleSeasonRows, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupTitleSeason
	for rows.Next() {
		var i GroupTitleSeason
		if err := rows.Scan(
			&i.GroupID,
			&i.TitleID,
			&i.Season,
			&i.Watched,
			&i.WatchedAt,
			&i.AddedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupTitleSeasonRowsForTitle = `-- name: GetGroupTitleSeasonRowsForTitle :many
SELECT group_id, title_id, season, watched, watched_at, added_at, updated_at FROM group_title_seasons WHERE group_id = $1 AND title_id = $2 ORDER BY season
`

type GetGroupTitleSeasonRowsForTitleParams struct {
	GroupID string
	TitleID string
}

func (q *Queries) GetGroupTitleSeasonRowsForTitle(ctx context.Context, arg GetGroupTitleSeasonRowsForTitleParams) ([]GroupTitleSeason, error) {
	rows, err := q.db.Query(ctx, getGroupTitleSeasonRowsForTitle, arg.GroupID, arg.TitleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupTitleSeason
	for rows.Next() {
		var i GroupTitleSeason
		if err := rows.Scan(
			&i.GroupID,
			&i.TitleID,
			&i.Season,
			&i.Watched,
			&i.WatchedAt,
			&i.AddedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupContainsTitle = `-- name: GroupContainsTitle :one
SELECT EXISTS (
    SELECT 1 FROM groups g
    WHERE g.id = $1 AND NOT g.deleted
      AND EXISTS (SELECT 1 FROM group_members m WHERE m.group_id = g.id AND m.user_id = $3)
      AND EXISTS (SELECT 1 FROM group_titles t WHERE t.group_id = g.id AND t.title_id = $2)
)
`

type GroupContainsTitleParams struct {
	ID      string
	TitleID string
	UserID  string
}

func (q *Queries) GroupContainsTitle(ctx context.Context, arg GroupContainsTitleParams) (bool, error) {
	row := q.db.QueryRow(ctx, groupContainsTitle, arg.ID, arg.TitleID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const groupExists = `-- name: GroupExists :one
SELECT EXISTS (
    SELECT 1 FROM groups g
    WHERE g.id = $1 AND NOT g.deleted
      AND EXISTS (SELECT 1 FROM group_members m WHERE m.group_id = g.id AND m.user_id = $2)
)
`

type GroupExistsParams struct {
	ID     string
	UserID string
}

func (q *Queries) GroupExists(ctx context.Context, arg GroupExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, groupExists, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const groupExistsNotDeleted = `-- name: GroupExistsNotDeleted :one
SELECT EXISTS (SELECT 1 FROM groups WHERE id = $1 AND NOT deleted)
`

func (q *Queries) GroupExistsNotDeleted(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, groupExistsNotDeleted, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const groupHasMember = `-- name: GroupHasMember :one
SELECT EXISTS (SELECT 1 FROM group_members WHERE group_id = $1 AND user_id = $2)
`

type GroupHasMemberParams struct {
	GroupID string
	UserID  string
}

func (q *Queries) GroupHasMember(ctx context.Context, arg GroupHasMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, groupHasMember, arg.GroupID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertGroup = `-- name: InsertGroup :one
INSERT INTO groups (id, name, description, owner_id, deleted, created_at, updated_at)
VALUES ($1, $2, $3, $4, false, $5, $6)
RETURNING id, name, description, owner_id, deleted, deleted_at, created_at, updated_at
`

type InsertGroupParams struct {
	ID          string
	Name        string
	Description string
	OwnerID     string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertGroup(ctx context.Context, arg InsertGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, insertGroup,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGroupFull = `-- name: InsertGroupFull :exec
INSERT INTO groups (id, name, description, owner_id, deleted, deleted_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertGroupFullParams struct {
	ID          string
	Name        string
	Description string
	OwnerID     string
	Deleted     bool
	DeletedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

// Migration-only (cmd/mongo-to-postgres): unlike InsertGroup, preserves the
// original deleted/deleted_at values from the Mongo document.
func (q *Queries) InsertGroupFull(ctx context.Context, arg InsertGroupFullParams) error {
	_, err := q.db.Exec(ctx, insertGroupFull,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.Deleted,
		arg.DeletedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const softDeleteGroupRow = `-- name: SoftDeleteGroupRow :execrows
UPDATE groups
SET deleted = true, deleted_at = now(), updated_at = now()
WHERE id = $1 AND NOT deleted
`

func (q *Queries) SoftDeleteGroupRow(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteGroupRow, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchGroup = `-- name: TouchGroup :exec
UPDATE groups SET updated_at = now() WHERE id = $1
`

func (q *Queries) TouchGroup(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchGroup, id)
	return err
}

const updateGroupInfoRow = `-- name: UpdateGroupInfoRow :execrows
UPDATE groups
SET name = $2, description = $3, updated_at = now()
WHERE id = $1 AND NOT deleted
`

type UpdateGroupInfoRowParams struct {
	ID          string
	Name        string
	Description string
}

func (q *Queries) UpdateGroupInfoRow(ctx context.Context, arg UpdateGroupInfoRowParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGroupInfoRow, arg.ID, arg.Name, arg.Description)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateGroupTitleWatchedRow = `-- name: UpdateGroupTitleWatchedRow :one
UPDATE group_titles
SET watched = $3, watched_at = $4, updated_at = $5
WHERE group_id = $1 AND title_id = $2
RETURNING group_id, title_id, title_type, watched, watched_at, added_at, updated_at
`

type UpdateGroupTitleWatchedRowParams struct {
	GroupID   string
	TitleID   string
	Watched   bool
	WatchedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateGroupTitleWatchedRow(ctx context.Context, arg UpdateGroupTitleWatchedRowParams) (GroupTitle, error) {
	row := q.db.QueryRow(ctx, updateGroupTitleWatchedRow,
		arg.GroupID,
		arg.TitleID,
		arg.Watched,
		arg.WatchedAt,
		arg.UpdatedAt,
	)
	var i GroupTitle
	err := row.Scan(
		&i.GroupID,
		&i.TitleID,
		&i.TitleType,
		&i.Watched,
		&i.WatchedAt,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGroupTitle = `-- name: UpsertGroupTitle :one
INSERT INTO group_titles (group_id, title_id, title_type, watched, watched_at, added_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (group_id, title_id) DO UPDATE
SET title_type = EXCLUDED.title_type,
    watched = EXCLUDED.watched,
    watched_at = EXCLUDED.watched_at,
    added_at = EXCLUDED.added_at,
    updated_at = EXCLUDED.updated_at
RETURNING group_id, title_id, title_type, watched, watched_at, added_at, updated_at
`

type UpsertGroupTitleParams struct {
	GroupID   string
	TitleID   string
	TitleType string
	Watched   bool
	WatchedAt pgtype.Timestamptz
	AddedAt   pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertGroupTitle(ctx context.Context, arg UpsertGroupTitleParams) (GroupTitle, error) {
	row := q.db.QueryRow(ctx, upsertGroupTitle,
		arg.GroupID,
		arg.TitleID,
		arg.TitleType,
		arg.Watched,
		arg.WatchedAt,
		arg.AddedAt,
		arg.UpdatedAt,
	)
	var i GroupTitle
	err := row.Scan(
		&i.GroupID,
		&i.TitleID,
		&i.TitleType,
		&i.Watched,
		&i.WatchedAt,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGroupTitleSeason = `-- name: UpsertGroupTitleSeason :one
INSERT INTO group_title_seasons (group_id, title_id, season, watched, watched_at, added_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (group_id, title_id, season) DO UPDATE
SET watched = EXCLUDED.watched,
    watched_at = EXCLUDED.watched_at,
    updated_at = EXCLUDED.updated_at
RETURNING group_id, title_id, season, watched, watched_at, added_at, updated_at
`

type UpsertGroupTitleSeasonParams struct {
	GroupID   string
	TitleID   string
	Season    string
	Watched   bool
	WatchedAt pgtype.Timestamptz
	AddedAt   pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertGroupTitleSeason(ctx context.Context, arg UpsertGroupTitleSeasonParams) (GroupTitleSeason, error) {
	row := q.db.QueryRow(ctx, upsertGroupTitleSeason,
		arg.GroupID,
		arg.TitleID,
		arg.Season,
		arg.Watched,
		arg.WatchedAt,
		arg.AddedAt,
		arg.UpdatedAt,
	)
	var i GroupTitleSeason
	err := row.Scan(
		&i.GroupID,
		&i.TitleID,
		&i.Season,
		&i.Watched,
		&i.WatchedAt,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}
