// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID        string
	TitleID   string
	UserID    string
	Comment   pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	GroupID   string
}

type CommentSeason struct {
	CommentID string
	Season    string
	Comment   string
	AddedAt   pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Group struct {
	ID          string
	Name        string
	Description string
	OwnerID     string
	Deleted     bool
	DeletedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type GroupMember struct {
	GroupID string
	UserID  string
}

type GroupTitle struct {
	GroupID   string
	TitleID   string
	Watched   bool
	WatchedAt pgtype.Timestamptz
	AddedAt   pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type GroupTitleSeason struct {
	GroupID   string
	TitleID   string
	Season    string
	Watched   bool
	WatchedAt pgtype.Timestamptz
	AddedAt   pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Rating struct {
	ID        string
	TitleID   string
	UserID    string
	Note      float32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	GroupID   string
}

type RatingSeason struct {
	RatingID  string
	Season    string
	Rating    float32
	AddedAt   pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Title struct {
	ID              string
	PrimaryTitle    string
	Type            string
	StartYear       int32
	RatingAggregate float64
	VoteCount       int32
	AddedAt         pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Metadata        []byte
}

type User struct {
	ID           string
	Name         string
	Email        string
	Username     string
	PasswordHash string
	AvatarUrl    pgtype.Text
	Role         string
	IsActive     bool
	LastLoginAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
