// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: placeholder.sql

package database

import (
	"context"
)

const placeholder = `-- name: Placeholder :one

SELECT 1::int AS placeholder
`

// Placeholder query. sqlc (all versions, incl. v1.30.0) errors with
// "no queries contained in paths" when sql/queries has zero queries, so a
// schema-only config cannot generate models.go/db.go on its own. This file
// exists solely to satisfy that requirement until Task 2 adds real queries
// (sql/queries/users.sql etc.) — delete this file once real queries exist.
func (q *Queries) Placeholder(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, placeholder)
	var placeholder int32
	err := row.Scan(&placeholder)
	return placeholder, err
}
