// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ratings.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRatingRow = `-- name: DeleteRatingRow :execrows
DELETE FROM ratings WHERE id = $1 AND user_id = $2
`

type DeleteRatingRowParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteRatingRow(ctx context.Context, arg DeleteRatingRowParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRatingRow, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRatingSeasons = `-- name: DeleteRatingSeasons :exec
DELETE FROM rating_seasons WHERE rating_id = $1
`

func (q *Queries) DeleteRatingSeasons(ctx context.Context, ratingID string) error {
	_, err := q.db.Exec(ctx, deleteRatingSeasons, ratingID)
	return err
}

const getRatingRowById = `-- name: GetRatingRowById :one
SELECT id, title_id, user_id, note, created_at, updated_at, group_id FROM ratings WHERE id = $1 AND user_id = $2
`

type GetRatingRowByIdParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetRatingRowById(ctx context.Context, arg GetRatingRowByIdParams) (Rating, error) {
	row := q.db.QueryRow(ctx, getRatingRowById, arg.ID, arg.UserID)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.TitleID,
		&i.UserID,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}

const getRatingRowByUserTitle = `-- name: GetRatingRowByUserTitle :one
SELECT id, title_id, user_id, note, created_at, updated_at, group_id FROM ratings WHERE user_id = $1 AND title_id = $2 AND group_id = $3
`

type GetRatingRowByUserTitleParams struct {
	UserID  string
	TitleID string
	GroupID string
}

func (q *Queries) GetRatingRowByUserTitle(ctx context.Context, arg GetRatingRowByUserTitleParams) (Rating, error) {
	row := q.db.QueryRow(ctx, getRatingRowByUserTitle, arg.UserID, arg.TitleID, arg.GroupID)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.TitleID,
		&i.UserID,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}

const getRatingRowsByTitleId = `-- name: GetRatingRowsByTitleId :many
SELECT id, title_id, user_id, note, created_at, updated_at, group_id FROM ratings WHERE title_id = $1 AND group_id = $2
`

type GetRatingRowsByTitleIdParams struct {
	TitleID string
	GroupID string
}

func (q *Queries) GetRatingRowsByTitleId(ctx context.Context, arg GetRatingRowsByTitleIdParams) ([]Rating, error) {
	rows, err := q.db.Query(ctx, getRatingRowsByTitleId, arg.TitleID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rating
	for rows.Next() {
		var i Rating
		if err := rows.Scan(
			&i.ID,
			&i.TitleID,
			&i.UserID,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRatingRowsByTitleIds = `-- name: GetRatingRowsByTitleIds :many
SELECT id, title_id, user_id, note, created_at, updated_at, group_id FROM ratings WHERE title_id = ANY($1::text[]) AND group_id = $2
`

type GetRatingRowsByTitleIdsParams struct {
	Column1 []string
	GroupID string
}

func (q *Queries) GetRatingRowsByTitleIds(ctx context.Context, arg GetRatingRowsByTitleIdsParams) ([]Rating, error) {
	rows, err := q.db.Query(ctx, getRatingRowsByTitleIds, arg.Column1, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rating
	for rows.Next() {
		var i Rating
		if err := rows.Scan(
			&i.ID,
			&i.TitleID,
			&i.UserID,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRatingSeasons = `-- name: GetRatingSeasons :many
SELECT rating_id, season, rating, added_at, updated_at FROM rating_seasons WHERE rating_id = $1
`

func (q *Queries) GetRatingSeasons(ctx context.Context, ratingID string) ([]RatingSeason, error) {
	rows, err := q.db.Query(ctx, getRatingSeasons, ratingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RatingSeason
	for rows.Next() {
		var i RatingSeason
		if err := rows.Scan(
			&i.RatingID,
			&i.Season,
			&i.Rating,
			&i.AddedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRatingSeasonsByRatingIds = `-- name: GetRatingSeasonsByRatingIds :many
SELECT rating_id, season, rating, added_at, updated_at FROM rating_seasons WHERE rating_id = ANY($1::text[])
`

func (q *Queries) GetRatingSeasonsByRatingIds(ctx context.Context, dollar_1 []string) ([]RatingSeason, error) {
	rows, err := q.db.Query(ctx, getRatingSeasonsByRatingIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RatingSeason
	for rows.Next() {
		var i RatingSeason
		if err := rows.Scan(
			&i.RatingID,
			&i.Season,
			&i.Rating,
			&i.AddedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRating = `-- name: InsertRating :one
INSERT INTO ratings (
    id, title_id, user_id, group_id, note, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, title_id, user_id, note, created_at, updated_at, group_id
`

type InsertRatingParams struct {
	ID        string
	TitleID   string
	UserID    string
	GroupID   string
	Note      float64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) InsertRating(ctx context.Context, arg InsertRatingParams) (Rating, error) {
	row := q.db.QueryRow(ctx, insertRating,
		arg.ID,
		arg.TitleID,
		arg.UserID,
		arg.GroupID,
		arg.Note,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.TitleID,
		&i.UserID,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}

const insertRatingSeason = `-- name: InsertRatingSeason :exec
INSERT INTO rating_seasons (
    rating_id, season, rating, added_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5
)
`

type InsertRatingSeasonParams struct {
	RatingID  string
	Season    string
	Rating    float64
	AddedAt   pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) InsertRatingSeason(ctx context.Context, arg InsertRatingSeasonParams) error {
	_, err := q.db.Exec(ctx, insertRatingSeason,
		arg.RatingID,
		arg.Season,
		arg.Rating,
		arg.AddedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateRatingRow = `-- name: UpdateRatingRow :one
UPDATE ratings
SET note = $3, updated_at = $4
WHERE id = $1 AND user_id = $2
RETURNING id, title_id, user_id, note, created_at, updated_at, group_id
`

type UpdateRatingRowParams struct {
	ID        string
	UserID    string
	Note      float64
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateRatingRow(ctx context.Context, arg UpdateRatingRowParams) (Rating, error) {
	row := q.db.QueryRow(ctx, updateRatingRow,
		arg.ID,
		arg.UserID,
		arg.Note,
		arg.UpdatedAt,
	)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.TitleID,
		&i.UserID,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}
