// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: titles.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTitle = `-- name: DeleteTitle :execrows
DELETE FROM titles WHERE id = $1
`

func (q *Queries) DeleteTitle(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTitle, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTitleById = `-- name: GetTitleById :one
SELECT id, primary_title, type, start_year, rating_aggregate, vote_count, added_at, updated_at, metadata FROM titles WHERE id = $1
`

func (q *Queries) GetTitleById(ctx context.Context, id string) (Title, error) {
	row := q.db.QueryRow(ctx, getTitleById, id)
	var i Title
	err := row.Scan(
		&i.ID,
		&i.PrimaryTitle,
		&i.Type,
		&i.StartYear,
		&i.RatingAggregate,
		&i.VoteCount,
		&i.AddedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const getTitleTypes = `-- name: GetTitleTypes :many
SELECT id, type FROM titles WHERE id = ANY($1::text[])
`

type GetTitleTypesRow struct {
	ID   string
	Type string
}

func (q *Queries) GetTitleTypes(ctx context.Context, dollar_1 []string) ([]GetTitleTypesRow, error) {
	rows, err := q.db.Query(ctx, getTitleTypes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTitleTypesRow
	for rows.Next() {
		var i GetTitleTypesRow
		if err := rows.Scan(&i.ID, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTitle = `-- name: InsertTitle :exec
INSERT INTO titles (
    id, primary_title, type, start_year, rating_aggregate, vote_count,
    added_at, updated_at, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type InsertTitleParams struct {
	ID              string
	PrimaryTitle    string
	Type            string
	StartYear       int32
	RatingAggregate float64
	VoteCount       int32
	AddedAt         pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Metadata        []byte
}

func (q *Queries) InsertTitle(ctx context.Context, arg InsertTitleParams) error {
	_, err := q.db.Exec(ctx, insertTitle,
		arg.ID,
		arg.PrimaryTitle,
		arg.Type,
		arg.StartYear,
		arg.RatingAggregate,
		arg.VoteCount,
		arg.AddedAt,
		arg.UpdatedAt,
		arg.Metadata,
	)
	return err
}

const titleExists = `-- name: TitleExists :one
SELECT EXISTS(SELECT 1 FROM titles WHERE id = $1)
`

func (q *Queries) TitleExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, titleExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
