// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: titles.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTitles = `-- name: CountTitles :one
SELECT count(*) FROM titles
`

func (q *Queries) CountTitles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTitles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTitle = `-- name: DeleteTitle :execrows
DELETE FROM titles WHERE id = $1
`

func (q *Queries) DeleteTitle(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTitle, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTitleById = `-- name: GetTitleById :one
SELECT id, primary_title, type, start_year, rating_aggregate, vote_count, added_at, updated_at, metadata FROM titles WHERE id = $1
`

func (q *Queries) GetTitleById(ctx context.Context, id string) (Title, error) {
	row := q.db.QueryRow(ctx, getTitleById, id)
	var i Title
	err := row.Scan(
		&i.ID,
		&i.PrimaryTitle,
		&i.Type,
		&i.StartYear,
		&i.RatingAggregate,
		&i.VoteCount,
		&i.AddedAt,
		&i.UpdatedAt,
		&i.Metadata,
	)
	return i, err
}

const getTitlesPage = `-- name: GetTitlesPage :many
SELECT id, primary_title, type, start_year, rating_aggregate, vote_count, added_at, updated_at, metadata
FROM titles
ORDER BY
    CASE WHEN $1::text IN ('', 'primaryTitle') AND NOT $2::bool THEN primary_title END ASC,
    CASE WHEN $1::text IN ('', 'primaryTitle') AND $2::bool     THEN primary_title END DESC,
    CASE WHEN $1::text = 'imdbRating' AND NOT $2::bool THEN rating_aggregate END ASC,
    CASE WHEN $1::text = 'imdbRating' AND $2::bool     THEN rating_aggregate END DESC,
    CASE WHEN $1::text = 'startYear'  AND NOT $2::bool THEN start_year END ASC,
    CASE WHEN $1::text = 'startYear'  AND $2::bool     THEN start_year END DESC,
    CASE WHEN $1::text = 'type'       AND NOT $2::bool THEN type END ASC,
    CASE WHEN $1::text = 'type'       AND $2::bool     THEN type END DESC,
    CASE WHEN $1::text = 'voteCount'  AND NOT $2::bool THEN vote_count END ASC,
    CASE WHEN $1::text = 'voteCount'  AND $2::bool     THEN vote_count END DESC,
    CASE WHEN $1::text = 'addedAt'    AND NOT $2::bool THEN added_at END ASC,
    CASE WHEN $1::text = 'addedAt'    AND $2::bool     THEN added_at END DESC,
    CASE WHEN $1::text = 'updatedAt'  AND NOT $2::bool THEN updated_at END ASC,
    CASE WHEN $1::text = 'updatedAt'  AND $2::bool     THEN updated_at END DESC,
    id ASC
LIMIT $4::bigint OFFSET $3::bigint
`

type GetTitlesPageParams struct {
	OrderBy    string
	Descending bool
	PageOffset int64
	PageSize   int64
}

// Static total ORDER BY (CONVENTIONS §6 — ends in id ASC). order_by arrives
// pre-normalized (unknown keys -> ”). No NULLS FIRST/LAST anywhere: Postgres'
// defaults keep deciding where NULL sort values land (added_at/updated_at are
// the only nullable keys), exactly as the hand-written version behaved.
//
// page_size/page_offset are cast to bigint so sqlc generates int64 params:
// Go's page/size are plain ints, and narrowing them to int32 could wrap
// negative (MAX_PAGE_SIZE is env-configurable without an upper bound), which
// Postgres rejects with "LIMIT/OFFSET must not be negative".
func (q *Queries) GetTitlesPage(ctx context.Context, arg GetTitlesPageParams) ([]Title, error) {
	rows, err := q.db.Query(ctx, getTitlesPage,
		arg.OrderBy,
		arg.Descending,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Title
	for rows.Next() {
		var i Title
		if err := rows.Scan(
			&i.ID,
			&i.PrimaryTitle,
			&i.Type,
			&i.StartYear,
			&i.RatingAggregate,
			&i.VoteCount,
			&i.AddedAt,
			&i.UpdatedAt,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTitle = `-- name: InsertTitle :exec
INSERT INTO titles (
    id, primary_title, type, start_year, rating_aggregate, vote_count,
    added_at, updated_at, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type InsertTitleParams struct {
	ID              string
	PrimaryTitle    string
	Type            string
	StartYear       int32
	RatingAggregate float64
	VoteCount       int32
	AddedAt         pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Metadata        []byte
}

func (q *Queries) InsertTitle(ctx context.Context, arg InsertTitleParams) error {
	_, err := q.db.Exec(ctx, insertTitle,
		arg.ID,
		arg.PrimaryTitle,
		arg.Type,
		arg.StartYear,
		arg.RatingAggregate,
		arg.VoteCount,
		arg.AddedAt,
		arg.UpdatedAt,
		arg.Metadata,
	)
	return err
}

const listTitleIds = `-- name: ListTitleIds :many
SELECT id FROM titles ORDER BY id
`

func (q *Queries) ListTitleIds(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listTitleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const titleExists = `-- name: TitleExists :one
SELECT EXISTS(SELECT 1 FROM titles WHERE id = $1)
`

func (q *Queries) TitleExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, titleExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateTitle = `-- name: UpdateTitle :execrows
UPDATE titles
SET primary_title = $2, type = $3, start_year = $4, rating_aggregate = $5,
    vote_count = $6, added_at = $7, updated_at = $8, metadata = $9
WHERE id = $1
`

type UpdateTitleParams struct {
	ID              string
	PrimaryTitle    string
	Type            string
	StartYear       int32
	RatingAggregate float64
	VoteCount       int32
	AddedAt         pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Metadata        []byte
}

func (q *Queries) UpdateTitle(ctx context.Context, arg UpdateTitleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTitle,
		arg.ID,
		arg.PrimaryTitle,
		arg.Type,
		arg.StartYear,
		arg.RatingAggregate,
		arg.VoteCount,
		arg.AddedAt,
		arg.UpdatedAt,
		arg.Metadata,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
