// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO group_members (group_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddGroupMemberParams struct {
	GroupID string
	UserID  string
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addGroupMember, arg.GroupID, arg.UserID)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id, name, email, username, password_hash, avatar_url, role,
    is_active, last_login_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
`

type CreateUserParams struct {
	ID           string
	Name         string
	Email        string
	Username     string
	PasswordHash string
	AvatarUrl    pgtype.Text
	Role         string
	IsActive     bool
	LastLoginAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.AvatarUrl,
		arg.Role,
		arg.IsActive,
		arg.LastLoginAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteUserById = `-- name: DeleteUserById :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUserById(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUserById, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, name, email, username, password_hash, avatar_url, role, is_active, last_login_at, created_at, updated_at FROM users ORDER BY id
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.AvatarUrl,
			&i.Role,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, email, username, password_hash, avatar_url, role, is_active, last_login_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsernameOrEmail = `-- name: GetUserByUsernameOrEmail :one
SELECT id, name, email, username, password_hash, avatar_url, role, is_active, last_login_at, created_at, updated_at FROM users
WHERE (username <> '' AND username = $1) OR (email <> '' AND email = $2)
`

type GetUserByUsernameOrEmailParams struct {
	Username string
	Email    string
}

func (q *Queries) GetUserByUsernameOrEmail(ctx context.Context, arg GetUserByUsernameOrEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameOrEmail, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserGroupIds = `-- name: GetUserGroupIds :many
SELECT g.id FROM group_members m
JOIN groups g ON g.id = m.group_id
WHERE m.user_id = $1 AND NOT g.deleted
`

func (q *Queries) GetUserGroupIds(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserGroupIds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members WHERE group_id = $1 AND user_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID string
	UserID  string
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.Exec(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	return err
}

const updateUserInfo = `-- name: UpdateUserInfo :one
UPDATE users
SET name = $2, email = $3, username = $4, updated_at = now()
WHERE id = $1
RETURNING id, name, email, username, password_hash, avatar_url, role, is_active, last_login_at, created_at, updated_at
`

type UpdateUserInfoParams struct {
	ID       string
	Name     string
	Email    string
	Username string
}

func (q *Queries) UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserInfo,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Username,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLastLoginAt = `-- name: UpdateUserLastLoginAt :one
UPDATE users
SET last_login_at = now()
WHERE id = $1
RETURNING id, name, email, username, password_hash, avatar_url, role, is_active, last_login_at, created_at, updated_at
`

func (q *Queries) UpdateUserLastLoginAt(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, updateUserLastLoginAt, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE id = $1)
`

func (q *Queries) UserExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
