package postgres

import (
	"context"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/stretchr/testify/require"

	"github.com/lealre/movies-backend/internal/models"
	"github.com/lealre/movies-backend/internal/store"
)

// newTestMovieComment builds a minimal, valid models.Comment for a movie
// (Comment set, no SeasonsComments), matching what
// services/comments.addCommentForMovie passes to Store.AddComment (no
// Id/CreatedAt/UpdatedAt: those are generated by the store).
func newTestMovieComment(t *testing.T, titleId, userId, text string) models.Comment {
	t.Helper()
	return models.Comment{
		TitleId: titleId,
		UserId:  userId,
		Comment: &text,
	}
}

// newTestSeriesComment builds a models.Comment with the given season ->
// comment-text entries (Comment nil, SeasonsComments set), matching what
// services/comments.addCommentForTVSeries passes to Store.AddComment.
func newTestSeriesComment(t *testing.T, titleId, userId string, seasons map[string]string) models.Comment {
	t.Helper()
	now := time.Now().UTC().Truncate(time.Second)
	seasonsComments := make(models.SeasonsComments, len(seasons))
	for season, text := range seasons {
		seasonsComments[season] = models.SeasonCommentItem{
			Comment:   text,
			AddedAt:   now,
			UpdatedAt: now,
		}
	}
	return models.Comment{
		TitleId:         titleId,
		UserId:          userId,
		SeasonsComments: &seasonsComments,
	}
}

func TestStore_AddComment_GetCommentById_Movie(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	titleId := "tt-movie-" + uuid.NewString()
	userId := "user-" + uuid.NewString()
	comment := newTestMovieComment(t, titleId, userId, "great movie")

	added, err := s.AddComment(ctx, comment)
	require.NoError(t, err)
	require.NotEmpty(t, added.Id, "AddComment must generate an id")
	require.Equal(t, titleId, added.TitleId)
	require.Equal(t, userId, added.UserId)
	require.NotNil(t, added.Comment)
	require.Equal(t, "great movie", *added.Comment)
	require.Nil(t, added.SeasonsComments, "a movie comment (no seasons) must round-trip with a nil SeasonsComments map")
	require.WithinDuration(t, time.Now(), added.CreatedAt, 5*time.Second)
	require.WithinDuration(t, time.Now(), added.UpdatedAt, 5*time.Second)

	got, err := s.GetCommentById(ctx, added.Id, userId)
	require.NoError(t, err)
	require.Equal(t, added, got)
}

func TestStore_AddComment_GetCommentById_Series(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	titleId := "tt-series-" + uuid.NewString()
	userId := "user-" + uuid.NewString()
	comment := newTestSeriesComment(t, titleId, userId, map[string]string{
		"1": "season 1 was great",
		"2": "season 2 was better",
	})

	added, err := s.AddComment(ctx, comment)
	require.NoError(t, err)
	require.Nil(t, added.Comment, "a series comment must round-trip with a nil top-level Comment")
	require.NotNil(t, added.SeasonsComments, "a series comment with seasons must round-trip with a non-nil SeasonsComments map")
	require.Len(t, *added.SeasonsComments, 2)
	require.Equal(t, "season 1 was great", (*added.SeasonsComments)["1"].Comment)
	require.Equal(t, "season 2 was better", (*added.SeasonsComments)["2"].Comment)

	got, err := s.GetCommentById(ctx, added.Id, userId)
	require.NoError(t, err)
	require.Nil(t, got.Comment)
	require.NotNil(t, got.SeasonsComments)
	require.Len(t, *got.SeasonsComments, 2)
	require.Equal(t, (*added.SeasonsComments)["1"].Comment, (*got.SeasonsComments)["1"].Comment)
	require.Equal(t, (*added.SeasonsComments)["2"].Comment, (*got.SeasonsComments)["2"].Comment)
	require.WithinDuration(t, (*added.SeasonsComments)["1"].AddedAt, (*got.SeasonsComments)["1"].AddedAt, time.Second)
}

func TestStore_GetUserCommentByTitleId(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	titleId := "tt-" + uuid.NewString()
	userId := "user-" + uuid.NewString()
	added, err := s.AddComment(ctx, newTestMovieComment(t, titleId, userId, "nice"))
	require.NoError(t, err)

	got, err := s.GetUserCommentByTitleId(ctx, titleId, userId)
	require.NoError(t, err)
	require.Equal(t, added, got)

	t.Run("not found", func(t *testing.T) {
		_, err := s.GetUserCommentByTitleId(ctx, "missing-title", "missing-user")
		require.ErrorIs(t, err, store.ErrRecordNotFound)
	})
}

func TestStore_GetCommentById_NotFound(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	_, err := s.GetCommentById(ctx, "missing-comment", "missing-user")
	require.ErrorIs(t, err, store.ErrRecordNotFound)
}

func TestStore_UpdateComment_ReplacesSeasonSet(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	titleId := "tt-" + uuid.NewString()
	userId := "user-" + uuid.NewString()
	added, err := s.AddComment(ctx, newTestSeriesComment(t, titleId, userId, map[string]string{
		"1": "first", "2": "second",
	}))
	require.NoError(t, err)
	require.Len(t, *added.SeasonsComments, 2)

	now := time.Now().UTC().Truncate(time.Second)
	newSeasons := models.SeasonsComments{
		"2": {Comment: "second-updated", AddedAt: (*added.SeasonsComments)["2"].AddedAt, UpdatedAt: now},
		"3": {Comment: "third", AddedAt: now, UpdatedAt: now},
	}
	update := models.Comment{
		Id:              added.Id,
		SeasonsComments: &newSeasons,
	}

	updated, err := s.UpdateComment(ctx, update, userId)
	require.NoError(t, err)
	require.NotNil(t, updated.SeasonsComments)
	require.Len(t, *updated.SeasonsComments, 2)
	require.NotContains(t, *updated.SeasonsComments, "1", "season 1 must have been dropped by the whole-map replace")
	require.Contains(t, *updated.SeasonsComments, "2")
	require.Contains(t, *updated.SeasonsComments, "3")
	require.Equal(t, "second-updated", (*updated.SeasonsComments)["2"].Comment)
	require.Equal(t, "third", (*updated.SeasonsComments)["3"].Comment)

	// Re-read from scratch must reflect exactly the new map, proving the
	// delete+reinsert was actually persisted (not just returned in-memory).
	reread, err := s.GetCommentById(ctx, added.Id, userId)
	require.NoError(t, err)
	require.NotNil(t, reread.SeasonsComments)
	require.Len(t, *reread.SeasonsComments, 2)
	require.NotContains(t, *reread.SeasonsComments, "1")
	require.Equal(t, "second-updated", (*reread.SeasonsComments)["2"].Comment)
	require.Equal(t, "third", (*reread.SeasonsComments)["3"].Comment)
}

func TestStore_UpdateComment_Movie(t *testing.T) {
	// Movie comments never have SeasonsComments; updating one (text-only)
	// must round-trip with SeasonsComments still nil.
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	titleId := "tt-" + uuid.NewString()
	userId := "user-" + uuid.NewString()
	added, err := s.AddComment(ctx, newTestMovieComment(t, titleId, userId, "original"))
	require.NoError(t, err)

	updatedText := "revised"
	updated, err := s.UpdateComment(ctx, models.Comment{Id: added.Id, Comment: &updatedText}, userId)
	require.NoError(t, err)
	require.Nil(t, updated.SeasonsComments)
	require.NotNil(t, updated.Comment)
	require.Equal(t, "revised", *updated.Comment)
}

func TestStore_UpdateComment_NotFound(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	text := "x"
	_, err := s.UpdateComment(ctx, models.Comment{Id: "missing-comment", Comment: &text}, "missing-user")
	require.ErrorIs(t, err, store.ErrRecordNotFound)
}

func TestStore_GetCommentsByTitleId_FiltersByUsersFromGroup(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	titleId := "tt-" + uuid.NewString()
	otherTitleId := "tt-other-" + uuid.NewString()

	c1, err := s.AddComment(ctx, newTestMovieComment(t, titleId, "user-1", "from user 1"))
	require.NoError(t, err)
	c2, err := s.AddComment(ctx, newTestSeriesComment(t, titleId, "user-2", map[string]string{"1": "s1"}))
	require.NoError(t, err)
	// user-3 also comments on titleId, but is not part of the group being
	// queried, so it must be excluded from the result.
	_, err = s.AddComment(ctx, newTestMovieComment(t, titleId, "user-3", "excluded"))
	require.NoError(t, err)
	_, err = s.AddComment(ctx, newTestMovieComment(t, otherTitleId, "user-1", "different title"))
	require.NoError(t, err)

	got, err := s.GetCommentsByTitleId(ctx, titleId, []string{"user-1", "user-2"})
	require.NoError(t, err)
	require.Len(t, got, 2)

	byId := map[string]models.Comment{}
	for _, c := range got {
		byId[c.Id] = c
	}
	require.Contains(t, byId, c1.Id)
	require.Contains(t, byId, c2.Id)
	require.Nil(t, byId[c1.Id].SeasonsComments)
	require.NotNil(t, byId[c2.Id].SeasonsComments)
	require.Len(t, *byId[c2.Id].SeasonsComments, 1)

	empty, err := s.GetCommentsByTitleId(ctx, "no-such-title", []string{"user-1"})
	require.NoError(t, err)
	require.Equal(t, []models.Comment{}, empty)
}

func TestStore_DeleteComment(t *testing.T) {
	t.Run("deletes comment and cascades its seasons", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		titleId := "tt-" + uuid.NewString()
		userId := "user-" + uuid.NewString()
		added, err := s.AddComment(ctx, newTestSeriesComment(t, titleId, userId, map[string]string{"1": "s1"}))
		require.NoError(t, err)

		count, err := s.DeleteComment(ctx, added.Id, userId)
		require.NoError(t, err)
		require.EqualValues(t, 1, count)

		_, err = s.GetCommentById(ctx, added.Id, userId)
		require.ErrorIs(t, err, store.ErrRecordNotFound)

		var seasonCount int
		err = s.pool.QueryRow(ctx, `SELECT count(*) FROM comment_seasons WHERE comment_id = $1`, added.Id).Scan(&seasonCount)
		require.NoError(t, err)
		require.Zero(t, seasonCount, "comment_seasons rows must cascade-delete with their parent comment")
	})

	t.Run("not found reports a zero count with no error", func(t *testing.T) {
		// mongodb.DeleteComment never maps a zero-affected delete to
		// store.ErrRecordNotFound; it just returns the (zero) count.
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		count, err := s.DeleteComment(ctx, "missing-comment", "missing-user")
		require.NoError(t, err)
		require.Zero(t, count)
	})
}

func TestAddComment_DuplicateUserTitle(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	titleId := "tt-" + uuid.NewString()
	userId := "user-" + uuid.NewString()
	comment := newTestMovieComment(t, titleId, userId, "first comment")

	// First AddComment should succeed
	added, err := s.AddComment(ctx, comment)
	require.NoError(t, err)
	require.NotEmpty(t, added.Id)

	// Second AddComment with same (user, title) pair should return ErrDuplicatedRecord
	duplicate := newTestMovieComment(t, titleId, userId, "second comment")
	_, err = s.AddComment(ctx, duplicate)
	require.ErrorIs(t, err, store.ErrDuplicatedRecord)
}
