package postgres

import (
	"context"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/stretchr/testify/require"

	"github.com/lealre/movies-backend/internal/models"
	"github.com/lealre/movies-backend/internal/store"
)

// newTestMovieComment builds a minimal, valid models.Comment for a movie
// (Comment set, no SeasonsComments), matching what
// services/comments.addCommentForMovie passes to Store.AddComment (no
// Id/CreatedAt/UpdatedAt: those are generated by the store). groupId is part
// of the comment's identity and is never empty.
func newTestMovieComment(t *testing.T, titleId, userId, groupId, text string) models.Comment {
	t.Helper()
	return models.Comment{
		TitleId: titleId,
		UserId:  userId,
		GroupId: groupId,
		Comment: &text,
	}
}

// newTestSeriesComment builds a models.Comment with the given season ->
// comment-text entries (Comment nil, SeasonsComments set), matching what
// services/comments.addCommentForTVSeries passes to Store.AddComment.
func newTestSeriesComment(t *testing.T, titleId, userId, groupId string, seasons map[string]string) models.Comment {
	t.Helper()
	now := time.Now().UTC().Truncate(time.Second)
	seasonsComments := make(models.SeasonsComments, len(seasons))
	for season, text := range seasons {
		seasonsComments[season] = models.SeasonCommentItem{
			Comment:   text,
			AddedAt:   now,
			UpdatedAt: now,
		}
	}
	return models.Comment{
		TitleId:         titleId,
		UserId:          userId,
		GroupId:         groupId,
		SeasonsComments: &seasonsComments,
	}
}

func TestStore_AddComment_GetCommentById_Movie(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	groupId := addTestGroup(t, s)
	titleId := "tt-movie-" + uuid.NewString()
	userId := "user-" + uuid.NewString()
	comment := newTestMovieComment(t, titleId, userId, groupId, "great movie")

	added, err := s.AddComment(ctx, comment)
	require.NoError(t, err)
	require.NotEmpty(t, added.Id, "AddComment must generate an id")
	require.Equal(t, titleId, added.TitleId)
	require.Equal(t, userId, added.UserId)
	require.Equal(t, groupId, added.GroupId, "the comment must round-trip with the group it was written in")
	require.NotNil(t, added.Comment)
	require.Equal(t, "great movie", *added.Comment)
	require.Nil(t, added.SeasonsComments, "a movie comment (no seasons) must round-trip with a nil SeasonsComments map")
	require.WithinDuration(t, time.Now(), added.CreatedAt, 5*time.Second)
	require.WithinDuration(t, time.Now(), added.UpdatedAt, 5*time.Second)

	got, err := s.GetCommentById(ctx, added.Id, userId)
	require.NoError(t, err)
	require.Equal(t, added, got)
}

func TestStore_AddComment_GetCommentById_Series(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	groupId := addTestGroup(t, s)
	titleId := "tt-series-" + uuid.NewString()
	userId := "user-" + uuid.NewString()
	comment := newTestSeriesComment(t, titleId, userId, groupId, map[string]string{
		"1": "season 1 was great",
		"2": "season 2 was better",
	})

	added, err := s.AddComment(ctx, comment)
	require.NoError(t, err)
	require.Equal(t, groupId, added.GroupId, "the comment must round-trip with the group it was written in")
	require.Nil(t, added.Comment, "a series comment must round-trip with a nil top-level Comment")
	require.NotNil(t, added.SeasonsComments, "a series comment with seasons must round-trip with a non-nil SeasonsComments map")
	require.Len(t, *added.SeasonsComments, 2)
	require.Equal(t, "season 1 was great", (*added.SeasonsComments)["1"].Comment)
	require.Equal(t, "season 2 was better", (*added.SeasonsComments)["2"].Comment)

	got, err := s.GetCommentById(ctx, added.Id, userId)
	require.NoError(t, err)
	require.Nil(t, got.Comment)
	require.NotNil(t, got.SeasonsComments)
	require.Len(t, *got.SeasonsComments, 2)
	require.Equal(t, (*added.SeasonsComments)["1"].Comment, (*got.SeasonsComments)["1"].Comment)
	require.Equal(t, (*added.SeasonsComments)["2"].Comment, (*got.SeasonsComments)["2"].Comment)
	require.WithinDuration(t, (*added.SeasonsComments)["1"].AddedAt, (*got.SeasonsComments)["1"].AddedAt, time.Second)
}

func TestStore_GetUserCommentByTitleId(t *testing.T) {
	t.Run("round trip", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		groupId := addTestGroup(t, s)
		titleId := "tt-" + uuid.NewString()
		userId := "user-" + uuid.NewString()
		added, err := s.AddComment(ctx, newTestMovieComment(t, titleId, userId, groupId, "nice"))
		require.NoError(t, err)

		got, err := s.GetUserCommentByTitleId(ctx, titleId, userId, groupId)
		require.NoError(t, err)
		require.Equal(t, added, got)
	})

	t.Run("resolves the requested group's row when the user commented twice", func(t *testing.T) {
		// The underlying query is a sqlc :one, which compiles to QueryRow and
		// silently discards every row after the first. Without the group_id
		// predicate this lookup returns an arbitrary one of the two rows.
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		groupA := addTestGroup(t, s)
		groupB := addTestGroup(t, s)
		titleId := "tt-" + uuid.NewString()
		userId := "user-" + uuid.NewString()

		inA, err := s.AddComment(ctx, newTestMovieComment(t, titleId, userId, groupA, "for group A"))
		require.NoError(t, err)
		inB, err := s.AddComment(ctx, newTestMovieComment(t, titleId, userId, groupB, "for group B"))
		require.NoError(t, err)

		gotA, err := s.GetUserCommentByTitleId(ctx, titleId, userId, groupA)
		require.NoError(t, err)
		require.Equal(t, inA.Id, gotA.Id, "the (user, title) lookup must resolve group A's row, not group B's")
		require.Equal(t, groupA, gotA.GroupId)
		require.Equal(t, "for group A", *gotA.Comment)

		gotB, err := s.GetUserCommentByTitleId(ctx, titleId, userId, groupB)
		require.NoError(t, err)
		require.Equal(t, inB.Id, gotB.Id, "the (user, title) lookup must resolve group B's row, not group A's")
		require.Equal(t, groupB, gotB.GroupId)
		require.Equal(t, "for group B", *gotB.Comment)
	})

	t.Run("a comment in another group is not visible to this group", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		groupA := addTestGroup(t, s)
		groupB := addTestGroup(t, s)
		titleId := "tt-" + uuid.NewString()
		userId := "user-" + uuid.NewString()

		_, err := s.AddComment(ctx, newTestMovieComment(t, titleId, userId, groupA, "only in A"))
		require.NoError(t, err)

		_, err = s.GetUserCommentByTitleId(ctx, titleId, userId, groupB)
		require.ErrorIs(t, err, store.ErrRecordNotFound, "group B must not see the comment written in group A")
	})

	t.Run("not found", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		_, err := s.GetUserCommentByTitleId(ctx, "missing-title", "missing-user", "missing-group")
		require.ErrorIs(t, err, store.ErrRecordNotFound)
	})
}

func TestStore_AddComment_SameTitleInTwoGroups(t *testing.T) {
	// A comment is a (user, title, group) fact: the same user may say
	// different things about the same title in two groups, and both rows stand
	// on their own.
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	groupA := addTestGroup(t, s)
	groupB := addTestGroup(t, s)
	titleId := "tt-" + uuid.NewString()
	userId := "user-" + uuid.NewString()

	inA, err := s.AddComment(ctx, newTestMovieComment(t, titleId, userId, groupA, "loved it"))
	require.NoError(t, err)
	inB, err := s.AddComment(ctx, newTestMovieComment(t, titleId, userId, groupB, "overrated"))
	require.NoError(t, err, "commenting on a title already commented on in another group must be allowed")

	require.NotEqual(t, inA.Id, inB.Id, "the two comments must be distinct rows")
	require.Equal(t, groupA, inA.GroupId)
	require.Equal(t, groupB, inB.GroupId)

	// Each group's read path sees exactly its own comment.
	commentsA, err := s.GetCommentsByTitleId(ctx, titleId, groupA)
	require.NoError(t, err)
	require.Len(t, commentsA, 1, "group A must see only its own comment on the title")
	require.Equal(t, inA.Id, commentsA[0].Id)
	require.Equal(t, "loved it", *commentsA[0].Comment)

	commentsB, err := s.GetCommentsByTitleId(ctx, titleId, groupB)
	require.NoError(t, err)
	require.Len(t, commentsB, 1, "group B must see only its own comment on the title")
	require.Equal(t, inB.Id, commentsB[0].Id)
	require.Equal(t, "overrated", *commentsB[0].Comment)

	// Updating one group's comment leaves the other untouched.
	revised := "second thoughts"
	_, err = s.UpdateComment(ctx, models.Comment{Id: inB.Id, Comment: &revised}, userId)
	require.NoError(t, err)

	rereadA, err := s.GetCommentById(ctx, inA.Id, userId)
	require.NoError(t, err)
	require.Equal(t, "loved it", *rereadA.Comment, "updating group B's comment must not touch group A's")
	rereadB, err := s.GetCommentById(ctx, inB.Id, userId)
	require.NoError(t, err)
	require.Equal(t, "second thoughts", *rereadB.Comment)
}

func TestStore_GetCommentById_NotFound(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	_, err := s.GetCommentById(ctx, "missing-comment", "missing-user")
	require.ErrorIs(t, err, store.ErrRecordNotFound)
}

func TestStore_UpdateComment_ReplacesSeasonSet(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	groupId := addTestGroup(t, s)
	titleId := "tt-" + uuid.NewString()
	userId := "user-" + uuid.NewString()
	added, err := s.AddComment(ctx, newTestSeriesComment(t, titleId, userId, groupId, map[string]string{
		"1": "first", "2": "second",
	}))
	require.NoError(t, err)
	require.Len(t, *added.SeasonsComments, 2)

	now := time.Now().UTC().Truncate(time.Second)
	newSeasons := models.SeasonsComments{
		"2": {Comment: "second-updated", AddedAt: (*added.SeasonsComments)["2"].AddedAt, UpdatedAt: now},
		"3": {Comment: "third", AddedAt: now, UpdatedAt: now},
	}
	update := models.Comment{
		Id:              added.Id,
		SeasonsComments: &newSeasons,
	}

	updated, err := s.UpdateComment(ctx, update, userId)
	require.NoError(t, err)
	require.Equal(t, groupId, updated.GroupId, "an update must not move the comment out of its group")
	require.NotNil(t, updated.SeasonsComments)
	require.Len(t, *updated.SeasonsComments, 2)
	require.NotContains(t, *updated.SeasonsComments, "1", "season 1 must have been dropped by the whole-map replace")
	require.Contains(t, *updated.SeasonsComments, "2")
	require.Contains(t, *updated.SeasonsComments, "3")
	require.Equal(t, "second-updated", (*updated.SeasonsComments)["2"].Comment)
	require.Equal(t, "third", (*updated.SeasonsComments)["3"].Comment)

	// Re-read from scratch must reflect exactly the new map, proving the
	// delete+reinsert was actually persisted (not just returned in-memory).
	reread, err := s.GetCommentById(ctx, added.Id, userId)
	require.NoError(t, err)
	require.NotNil(t, reread.SeasonsComments)
	require.Len(t, *reread.SeasonsComments, 2)
	require.NotContains(t, *reread.SeasonsComments, "1")
	require.Equal(t, "second-updated", (*reread.SeasonsComments)["2"].Comment)
	require.Equal(t, "third", (*reread.SeasonsComments)["3"].Comment)
}

func TestStore_SeriesComment_PerSeasonPathsResolveTheRightGroup(t *testing.T) {
	// The TV-series add/update flow looks its row up by (user, title, group)
	// and then replaces that row's whole season map. With two groups holding a
	// comment on the same series, each side must move independently.
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	groupA := addTestGroup(t, s)
	groupB := addTestGroup(t, s)
	titleId := "tt-series-" + uuid.NewString()
	userId := "user-" + uuid.NewString()

	inA, err := s.AddComment(ctx, newTestSeriesComment(t, titleId, userId, groupA, map[string]string{"1": "A season 1"}))
	require.NoError(t, err)
	inB, err := s.AddComment(ctx, newTestSeriesComment(t, titleId, userId, groupB, map[string]string{
		"1": "B season 1", "2": "B season 2",
	}))
	require.NoError(t, err)

	// The add path's "does this user already have a comment here?" lookup must
	// return the group's own row, with the group's own seasons.
	lookupA, err := s.GetUserCommentByTitleId(ctx, titleId, userId, groupA)
	require.NoError(t, err)
	require.Equal(t, inA.Id, lookupA.Id)
	require.NotNil(t, lookupA.SeasonsComments)
	require.Len(t, *lookupA.SeasonsComments, 1, "group A's row must carry only group A's seasons")
	require.Equal(t, "A season 1", (*lookupA.SeasonsComments)["1"].Comment)

	lookupB, err := s.GetUserCommentByTitleId(ctx, titleId, userId, groupB)
	require.NoError(t, err)
	require.Equal(t, inB.Id, lookupB.Id)
	require.Len(t, *lookupB.SeasonsComments, 2, "group B's row must carry only group B's seasons")

	// Add a season to group B's comment, the way the series update path does:
	// take the row it just resolved, extend its map, write it back.
	now := time.Now().UTC().Truncate(time.Second)
	seasonsB := *lookupB.SeasonsComments
	seasonsB["3"] = models.SeasonCommentItem{Comment: "B season 3", AddedAt: now, UpdatedAt: now}
	_, err = s.UpdateComment(ctx, models.Comment{Id: lookupB.Id, SeasonsComments: &seasonsB}, userId)
	require.NoError(t, err)

	rereadB, err := s.GetUserCommentByTitleId(ctx, titleId, userId, groupB)
	require.NoError(t, err)
	require.Len(t, *rereadB.SeasonsComments, 3)
	require.Equal(t, "B season 3", (*rereadB.SeasonsComments)["3"].Comment)

	rereadA, err := s.GetUserCommentByTitleId(ctx, titleId, userId, groupA)
	require.NoError(t, err)
	require.Equal(t, inA.Id, rereadA.Id)
	require.Len(t, *rereadA.SeasonsComments, 1, "group A's seasons must be untouched by an update in group B")
	require.Equal(t, "A season 1", (*rereadA.SeasonsComments)["1"].Comment)
}

func TestStore_UpdateComment_Movie(t *testing.T) {
	// Movie comments never have SeasonsComments; updating one (text-only)
	// must round-trip with SeasonsComments still nil.
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	groupId := addTestGroup(t, s)
	titleId := "tt-" + uuid.NewString()
	userId := "user-" + uuid.NewString()
	added, err := s.AddComment(ctx, newTestMovieComment(t, titleId, userId, groupId, "original"))
	require.NoError(t, err)

	updatedText := "revised"
	updated, err := s.UpdateComment(ctx, models.Comment{Id: added.Id, Comment: &updatedText}, userId)
	require.NoError(t, err)
	require.Nil(t, updated.SeasonsComments)
	require.NotNil(t, updated.Comment)
	require.Equal(t, "revised", *updated.Comment)
	require.Equal(t, groupId, updated.GroupId)
}

func TestStore_UpdateComment_NotFound(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	text := "x"
	_, err := s.UpdateComment(ctx, models.Comment{Id: "missing-comment", Comment: &text}, "missing-user")
	require.ErrorIs(t, err, store.ErrRecordNotFound)
}

func TestStore_GetCommentsByTitleId_FiltersByGroup(t *testing.T) {
	// Comments are read through the group they belong to: the row carries its
	// group, so this filters on group_id rather than on the group's member
	// list. A comment written in another group must never appear here, even
	// when its author is also a member of the requesting group.
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	groupId := addTestGroup(t, s)
	otherGroupId := addTestGroup(t, s)
	titleId := "tt-" + uuid.NewString()
	otherTitleId := "tt-other-" + uuid.NewString()

	c1, err := s.AddComment(ctx, newTestMovieComment(t, titleId, "user-1", groupId, "from user 1"))
	require.NoError(t, err)
	c2, err := s.AddComment(ctx, newTestSeriesComment(t, titleId, "user-2", groupId, map[string]string{"1": "s1"}))
	require.NoError(t, err)
	// user-1 comments on the same title in another group: same author, same
	// title, different fact — it must be excluded from this group's read.
	excluded, err := s.AddComment(ctx, newTestMovieComment(t, titleId, "user-1", otherGroupId, "excluded, other group"))
	require.NoError(t, err)
	// A comment by a user this group never sees, in the other group.
	_, err = s.AddComment(ctx, newTestMovieComment(t, titleId, "user-3", otherGroupId, "excluded, other user"))
	require.NoError(t, err)
	// Same group, different title.
	_, err = s.AddComment(ctx, newTestMovieComment(t, otherTitleId, "user-1", groupId, "different title"))
	require.NoError(t, err)

	got, err := s.GetCommentsByTitleId(ctx, titleId, groupId)
	require.NoError(t, err)
	require.Len(t, got, 2, "only the requested group's comments on the title may be returned")

	byId := map[string]models.Comment{}
	for _, c := range got {
		byId[c.Id] = c
		require.Equal(t, groupId, c.GroupId, "every returned comment must belong to the requested group")
	}
	require.Contains(t, byId, c1.Id)
	require.Contains(t, byId, c2.Id)
	require.NotContains(t, byId, excluded.Id, "a comment from another group leaked into this group's read")
	require.Nil(t, byId[c1.Id].SeasonsComments)
	require.NotNil(t, byId[c2.Id].SeasonsComments)
	require.Len(t, *byId[c2.Id].SeasonsComments, 1)

	// The mirror image: the other group sees only its own two.
	other, err := s.GetCommentsByTitleId(ctx, titleId, otherGroupId)
	require.NoError(t, err)
	require.Len(t, other, 2, "the other group must see exactly its own two comments")
	for _, c := range other {
		require.Equal(t, otherGroupId, c.GroupId)
	}

	empty, err := s.GetCommentsByTitleId(ctx, "no-such-title", groupId)
	require.NoError(t, err)
	require.Equal(t, []models.Comment{}, empty)
}

func TestStore_DeleteComment(t *testing.T) {
	t.Run("deletes comment and cascades its seasons", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		groupId := addTestGroup(t, s)
		titleId := "tt-" + uuid.NewString()
		userId := "user-" + uuid.NewString()
		added, err := s.AddComment(ctx, newTestSeriesComment(t, titleId, userId, groupId, map[string]string{"1": "s1"}))
		require.NoError(t, err)

		count, err := s.DeleteComment(ctx, added.Id, userId, groupId)
		require.NoError(t, err)
		require.EqualValues(t, 1, count)

		_, err = s.GetCommentById(ctx, added.Id, userId)
		require.ErrorIs(t, err, store.ErrRecordNotFound)

		var seasonCount int
		err = s.pool.QueryRow(ctx, `SELECT count(*) FROM comment_seasons WHERE comment_id = $1`, added.Id).Scan(&seasonCount)
		require.NoError(t, err)
		require.Zero(t, seasonCount, "comment_seasons rows must cascade-delete with their parent comment")
	})

	t.Run("deletes only the targeted group's comment", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		groupA := addTestGroup(t, s)
		groupB := addTestGroup(t, s)
		titleId := "tt-" + uuid.NewString()
		userId := "user-" + uuid.NewString()

		inA, err := s.AddComment(ctx, newTestMovieComment(t, titleId, userId, groupA, "in A"))
		require.NoError(t, err)
		inB, err := s.AddComment(ctx, newTestMovieComment(t, titleId, userId, groupB, "in B"))
		require.NoError(t, err)

		count, err := s.DeleteComment(ctx, inA.Id, userId, groupA)
		require.NoError(t, err)
		require.EqualValues(t, 1, count)

		_, err = s.GetUserCommentByTitleId(ctx, titleId, userId, groupA)
		require.ErrorIs(t, err, store.ErrRecordNotFound)

		survivor, err := s.GetUserCommentByTitleId(ctx, titleId, userId, groupB)
		require.NoError(t, err, "deleting group A's comment must leave group B's alone")
		require.Equal(t, inB.Id, survivor.Id)
	})

	t.Run("a comment id from another group deletes nothing", func(t *testing.T) {
		// group_id is part of the key the delete matches on, so an id naming the
		// same user's comment in a different group is simply not there.
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		groupA := addTestGroup(t, s)
		groupB := addTestGroup(t, s)
		titleId := "tt-" + uuid.NewString()
		userId := "user-" + uuid.NewString()

		inA, err := s.AddComment(ctx, newTestMovieComment(t, titleId, userId, groupA, "in A"))
		require.NoError(t, err)
		inB, err := s.AddComment(ctx, newTestMovieComment(t, titleId, userId, groupB, "in B"))
		require.NoError(t, err)

		count, err := s.DeleteComment(ctx, inB.Id, userId, groupA)
		require.NoError(t, err)
		require.Zero(t, count, "group B's comment id must not be deletable through group A")

		stillA, err := s.GetUserCommentByTitleId(ctx, titleId, userId, groupA)
		require.NoError(t, err, "group A's comment must survive a delete addressed with group B's id")
		require.Equal(t, inA.Id, stillA.Id)

		stillB, err := s.GetUserCommentByTitleId(ctx, titleId, userId, groupB)
		require.NoError(t, err, "group B's comment must survive a delete scoped to group A")
		require.Equal(t, inB.Id, stillB.Id)
	})

	t.Run("not found reports a zero count with no error", func(t *testing.T) {
		// A zero-affected delete is not mapped to
		// store.ErrRecordNotFound; it just returns the (zero) count.
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		count, err := s.DeleteComment(ctx, "missing-comment", "missing-user", "missing-group")
		require.NoError(t, err)
		require.Zero(t, count)
	})
}

func TestAddComment_DuplicateUserTitle(t *testing.T) {
	t.Run("same user, title and group is a duplicate", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		groupId := addTestGroup(t, s)
		titleId := "tt-" + uuid.NewString()
		userId := "user-" + uuid.NewString()

		added, err := s.AddComment(ctx, newTestMovieComment(t, titleId, userId, groupId, "first comment"))
		require.NoError(t, err)
		require.NotEmpty(t, added.Id)

		_, err = s.AddComment(ctx, newTestMovieComment(t, titleId, userId, groupId, "second comment"))
		require.ErrorIs(t, err, store.ErrDuplicatedRecord, "a second comment on the same title in the same group must be refused")
	})

	t.Run("same user and title in a different group is not a duplicate", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		groupA := addTestGroup(t, s)
		groupB := addTestGroup(t, s)
		titleId := "tt-" + uuid.NewString()
		userId := "user-" + uuid.NewString()

		_, err := s.AddComment(ctx, newTestMovieComment(t, titleId, userId, groupA, "first comment"))
		require.NoError(t, err)

		second, err := s.AddComment(ctx, newTestMovieComment(t, titleId, userId, groupB, "second comment"))
		require.NoError(t, err, "the same (user, title) in another group is a different fact and must be accepted")
		require.Equal(t, groupB, second.GroupId)
	})
}

// TestStore_Comments_CascadeOnGroupDelete is the comments half of the
// ON DELETE CASCADE contract asserted in ratings_test.go.
func TestStore_Comments_CascadeOnGroupDelete(t *testing.T) {
	t.Run("hard-deleting a group removes its comments", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		groupA := addTestGroup(t, s)
		groupB := addTestGroup(t, s)
		titleId := "tt-cascade-" + uuid.NewString()
		userId := "user-cascade-" + uuid.NewString()

		_, err := s.AddComment(ctx, newTestMovieComment(t, titleId, userId, groupA, "in the doomed group"))
		require.NoError(t, err, "failed to seed the comment in the group being deleted")
		_, err = s.AddComment(ctx, newTestMovieComment(t, titleId, userId, groupB, "in the surviving group"))
		require.NoError(t, err, "failed to seed the comment in the surviving group")

		_, err = newTestPool(t).Exec(ctx, `DELETE FROM groups WHERE id = $1`, groupA)
		require.NoError(t, err, "hard-deleting a group must succeed, not be blocked by the comments foreign key")

		gone, err := s.GetCommentsByTitleId(ctx, titleId, groupA)
		require.NoError(t, err)
		require.Empty(t, gone, "the deleted group's comments must be gone")

		kept, err := s.GetCommentsByTitleId(ctx, titleId, groupB)
		require.NoError(t, err)
		require.Len(t, kept, 1, "the other group's comment must survive the cascade")
	})
}
