package postgres

import (
	"context"
	"fmt"
	"math"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/stretchr/testify/require"

	"github.com/lealre/movies-backend/internal/database"
	"github.com/lealre/movies-backend/internal/generics"
	"github.com/lealre/movies-backend/internal/models"
	"github.com/lealre/movies-backend/internal/store"
)

// newTestGroup builds the minimal models.Group the service layer passes to
// Store.CreateGroup: owner-only Users slice, empty (non-nil) Titles map, and
// no Id/timestamps (those are generated by the store).
func newTestGroup(t *testing.T, name, ownerId string) models.Group {
	t.Helper()
	return models.Group{
		Name:        name,
		Description: "",
		OwnerId:     ownerId,
		Users:       []string{ownerId},
		Titles:      models.GroupTitles{},
	}
}

// addTestUser inserts and returns a fresh user id, so membership rows point at
// real users (needed for GetUsersFromGroup's JOIN and the member's own Groups).
func addTestUser(t *testing.T, s *Store) string {
	t.Helper()
	u := newTestUser(t)
	require.NoError(t, s.AddUser(context.Background(), u))
	return u.Id
}

func flexDate(tm time.Time) *generics.FlexibleDate {
	return &generics.FlexibleDate{Time: &tm}
}

func boolPtr(b bool) *bool { return &b }

// addGroupTitleRow upserts a group_titles row via the generated query
// directly, bypassing the store's higher-level helpers (AddNewGroupTitle
// always creates a movie with watched=false and stamps "now") so tests can
// pin every column GetGroupTitlesPage filters or sorts on — title_type,
// watched, watchedAt (nil allowed), addedAt, updatedAt — independently.
func addGroupTitleRow(t *testing.T, s *Store, groupId, titleId, titleType string, watched bool, watchedAt *time.Time, addedAt, updatedAt time.Time) {
	t.Helper()
	_, err := s.q.UpsertGroupTitle(context.Background(), database.UpsertGroupTitleParams{
		GroupID:   groupId,
		TitleID:   titleId,
		TitleType: titleType,
		Watched:   watched,
		WatchedAt: ptrToTimestamptz(watchedAt),
		AddedAt:   timeToTimestamptz(addedAt),
		UpdatedAt: timeToTimestamptz(updatedAt),
	})
	require.NoError(t, err)
}

// addGroupTitleSeasonRow upserts a group_title_seasons row directly. Its
// parent group_titles row (via addGroupTitleRow) must already exist — the
// schema's FK requires it.
func addGroupTitleSeasonRow(t *testing.T, s *Store, groupId, titleId, season string, watched bool, watchedAt *time.Time, addedAt, updatedAt time.Time) {
	t.Helper()
	_, err := s.q.UpsertGroupTitleSeason(context.Background(), database.UpsertGroupTitleSeasonParams{
		GroupID:   groupId,
		TitleID:   titleId,
		Season:    season,
		Watched:   watched,
		WatchedAt: ptrToTimestamptz(watchedAt),
		AddedAt:   timeToTimestamptz(addedAt),
		UpdatedAt: timeToTimestamptz(updatedAt),
	})
	require.NoError(t, err)
}

// addTestTitleWithType builds and inserts a minimal movie title (via
// newTestMovieTitle) with its type overridden, for titleTypes-filter and
// type-sort tests.
func addTestTitleWithType(t *testing.T, s *Store, id, primaryTitle, titleType string) models.Title {
	t.Helper()
	title := newTestMovieTitle(t, id, primaryTitle, 5.0)
	title.Type = titleType
	require.NoError(t, s.AddTitle(context.Background(), title))
	return title
}

func TestStore_CreateGroup_GetGroupById(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	created, err := s.CreateGroup(ctx, newTestGroup(t, "movie night", owner))
	require.NoError(t, err)
	require.NotEmpty(t, created.Id, "CreateGroup must generate an id")
	require.Equal(t, "movie night", created.Name)
	require.Equal(t, owner, created.OwnerId)
	require.Equal(t, []string{owner}, created.Users)
	require.NotNil(t, created.Titles, "Titles must be a non-nil (empty) map")
	require.Empty(t, created.Titles)
	require.False(t, created.Deleted)
	require.WithinDuration(t, time.Now(), created.CreatedAt, 5*time.Second)

	got, err := s.GetGroupById(ctx, created.Id, owner)
	require.NoError(t, err)
	require.Equal(t, created.Id, got.Id)
	require.Equal(t, "movie night", got.Name)
	require.Contains(t, got.Users, owner, "owner must be auto-added as a member")
	require.NotNil(t, got.Titles)
	require.Empty(t, got.Titles)
}

func TestStore_GetGroupById_NonMember(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	created, err := s.CreateGroup(ctx, newTestGroup(t, "private", owner))
	require.NoError(t, err)

	_, err = s.GetGroupById(ctx, created.Id, "outsider")
	require.ErrorIs(t, err, store.ErrRecordNotFound)
}

func TestStore_GetGroupById_SoftDeleted(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	created, err := s.CreateGroup(ctx, newTestGroup(t, "temp", owner))
	require.NoError(t, err)

	require.NoError(t, s.SoftDeleteGroup(ctx, created.Id))

	_, err = s.GetGroupById(ctx, created.Id, owner)
	require.ErrorIs(t, err, store.ErrRecordNotFound, "a soft-deleted group must not be found")

	// SoftDeleteGroup is idempotent-guarded: deleting again reports not found.
	err = s.SoftDeleteGroup(ctx, created.Id)
	require.ErrorIs(t, err, store.ErrRecordNotFound)
}

func TestStore_AddUserToGroup(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	member := addTestUser(t, s)
	created, err := s.CreateGroup(ctx, newTestGroup(t, "crew", owner))
	require.NoError(t, err)

	require.NoError(t, s.AddUserToGroup(ctx, created.Id, owner, member))

	got, err := s.GetGroupById(ctx, created.Id, member)
	require.NoError(t, err)
	require.Contains(t, got.Users, owner)
	require.Contains(t, got.Users, member)
	require.Len(t, got.Users, 2)

	// The new member's own user Groups must now include this group.
	memberUser, err := s.GetUserById(ctx, member)
	require.NoError(t, err)
	require.Contains(t, memberUser.Groups, created.Id)

	t.Run("non-owner guard reports not found", func(t *testing.T) {
		err := s.AddUserToGroup(ctx, created.Id, "not-a-member", "someone")
		require.ErrorIs(t, err, store.ErrRecordNotFound)
	})
}

func TestStore_GetUsersFromGroup(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	member := addTestUser(t, s)
	created, err := s.CreateGroup(ctx, newTestGroup(t, "watch club", owner))
	require.NoError(t, err)
	require.NoError(t, s.AddUserToGroup(ctx, created.Id, owner, member))

	users, err := s.GetUsersFromGroup(ctx, created.Id, owner)
	require.NoError(t, err)
	require.Len(t, users, 2)

	ids := []string{users[0].Id, users[1].Id}
	require.ElementsMatch(t, []string{owner, member}, ids)
	for _, u := range users {
		require.Contains(t, u.Groups, created.Id, "each member's Groups must include the group")
	}

	t.Run("non-member is refused", func(t *testing.T) {
		_, err := s.GetUsersFromGroup(ctx, created.Id, "outsider")
		require.ErrorIs(t, err, store.ErrRecordNotFound)
	})
}

func TestStore_AddNewGroupTitle(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	created, err := s.CreateGroup(ctx, newTestGroup(t, "queue", owner))
	require.NoError(t, err)

	titleId := "tt-" + uuid.NewString()
	require.NoError(t, s.AddNewGroupTitle(ctx, created.Id, titleId))

	got, err := s.GetGroupById(ctx, created.Id, owner)
	require.NoError(t, err)
	require.Contains(t, got.Titles, titleId)
	item := got.Titles[titleId]
	require.Equal(t, titleId, item.TitleId)
	require.Equal(t, "movie", item.TitleType)
	require.False(t, item.Watched)
	require.Nil(t, item.SeasonsWatched, "a freshly added movie must have nil SeasonsWatched")
	require.Nil(t, item.WatchedAt)

	// GroupContainsTitle reflects the new title; a bogus title does not.
	contains, err := s.GroupContainsTitle(ctx, created.Id, titleId, owner)
	require.NoError(t, err)
	require.True(t, contains)
	contains, err = s.GroupContainsTitle(ctx, created.Id, "tt-nope", owner)
	require.NoError(t, err)
	require.False(t, contains)
}

func TestStore_UpdateGroupTitleWatchedForMovie(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	created, err := s.CreateGroup(ctx, newTestGroup(t, "movies", owner))
	require.NoError(t, err)
	titleId := "tt-" + uuid.NewString()
	require.NoError(t, s.AddNewGroupTitle(ctx, created.Id, titleId))

	when := time.Now().UTC().Truncate(time.Second)
	item, err := s.UpdateGroupTitleWatchedForMovie(ctx, created.Id, titleId, boolPtr(true), flexDate(when))
	require.NoError(t, err)
	require.NotNil(t, item)
	require.True(t, item.Watched)
	require.NotNil(t, item.WatchedAt)
	require.WithinDuration(t, when, *item.WatchedAt, time.Second)
	require.Nil(t, item.SeasonsWatched)

	// Persisted: re-read shows watched.
	got, err := s.GetGroupById(ctx, created.Id, owner)
	require.NoError(t, err)
	require.True(t, got.Titles[titleId].Watched)

	t.Run("watched=false clears watchedAt when cleared by caller", func(t *testing.T) {
		// The service passes a nil-Time FlexibleDate to clear watchedAt.
		item, err := s.UpdateGroupTitleWatchedForMovie(ctx, created.Id, titleId, boolPtr(false), &generics.FlexibleDate{Time: nil})
		require.NoError(t, err)
		require.False(t, item.Watched)
		require.Nil(t, item.WatchedAt, "watchedAt must be cleared to nil")
	})

	t.Run("no fields to update is an error", func(t *testing.T) {
		_, err := s.UpdateGroupTitleWatchedForMovie(ctx, created.Id, titleId, nil, nil)
		require.Error(t, err)
	})

	t.Run("missing title is not found", func(t *testing.T) {
		_, err := s.UpdateGroupTitleWatchedForMovie(ctx, created.Id, "tt-missing", boolPtr(true), nil)
		require.ErrorIs(t, err, store.ErrRecordNotFound)
	})
}

func TestStore_UpdateGroupTitleWatchedForTVSeries(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	created, err := s.CreateGroup(ctx, newTestGroup(t, "series", owner))
	require.NoError(t, err)
	titleId := "tt-" + uuid.NewString()
	require.NoError(t, s.AddNewGroupTitle(ctx, created.Id, titleId))

	when1 := time.Now().UTC().Truncate(time.Second)

	// Mark season 1 watched: top-level watched becomes true (at least one
	// season watched) and top-level watchedAt is season 1's date.
	item, err := s.UpdateGroupTitleWatchedForTVSeries(ctx, created.Id, titleId, boolPtr(true), flexDate(when1), 1, owner)
	require.NoError(t, err)
	require.NotNil(t, item)
	require.NotNil(t, item.SeasonsWatched, "SeasonsWatched must become a non-nil map")
	require.Contains(t, *item.SeasonsWatched, "1")
	require.True(t, (*item.SeasonsWatched)["1"].Watched)
	require.True(t, item.Watched, "top-level watched must be true when >=1 season is watched")
	require.NotNil(t, item.WatchedAt)
	require.WithinDuration(t, when1, *item.WatchedAt, time.Second)

	// Add season 2 with a LATER date: top-level watchedAt must move to the max.
	when2 := when1.Add(48 * time.Hour)
	item, err = s.UpdateGroupTitleWatchedForTVSeries(ctx, created.Id, titleId, boolPtr(true), flexDate(when2), 2, owner)
	require.NoError(t, err)
	require.Len(t, *item.SeasonsWatched, 2)
	require.True(t, item.Watched)
	require.WithinDuration(t, when2, *item.WatchedAt, time.Second, "top-level watchedAt must be the latest watched season's date")

	// Un-watch season 2 (service clears its watchedAt): season 1 still watched,
	// so top-level stays watched with season 1's earlier date.
	item, err = s.UpdateGroupTitleWatchedForTVSeries(ctx, created.Id, titleId, boolPtr(false), &generics.FlexibleDate{Time: nil}, 2, owner)
	require.NoError(t, err)
	require.False(t, (*item.SeasonsWatched)["2"].Watched)
	require.Nil(t, (*item.SeasonsWatched)["2"].WatchedAt)
	require.True(t, item.Watched, "still watched because season 1 remains watched")
	require.WithinDuration(t, when1, *item.WatchedAt, time.Second)

	// Un-watch season 1 too: no season watched => top-level watched=false,
	// watchedAt=nil.
	item, err = s.UpdateGroupTitleWatchedForTVSeries(ctx, created.Id, titleId, boolPtr(false), &generics.FlexibleDate{Time: nil}, 1, owner)
	require.NoError(t, err)
	require.False(t, item.Watched, "no watched seasons => top-level watched=false")
	require.Nil(t, item.WatchedAt, "no watched seasons => top-level watchedAt=nil")

	// The whole thing persists across a fresh read.
	got, err := s.GetGroupById(ctx, created.Id, owner)
	require.NoError(t, err)
	gt := got.Titles[titleId]
	require.NotNil(t, gt.SeasonsWatched)
	require.Len(t, *gt.SeasonsWatched, 2)
	require.False(t, gt.Watched)

	t.Run("non-member guard", func(t *testing.T) {
		_, err := s.UpdateGroupTitleWatchedForTVSeries(ctx, created.Id, titleId, boolPtr(true), nil, 1, "outsider")
		require.ErrorIs(t, err, store.ErrRecordNotFound)
	})
}

func TestStore_RemoveTitleFromGroup_CascadesSeasons(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	created, err := s.CreateGroup(ctx, newTestGroup(t, "cascade", owner))
	require.NoError(t, err)
	titleId := "tt-" + uuid.NewString()
	require.NoError(t, s.AddNewGroupTitle(ctx, created.Id, titleId))
	_, err = s.UpdateGroupTitleWatchedForTVSeries(ctx, created.Id, titleId, boolPtr(true), nil, 1, owner)
	require.NoError(t, err)

	require.NoError(t, s.RemoveTitleFromGroup(ctx, created.Id, titleId, owner))

	got, err := s.GetGroupById(ctx, created.Id, owner)
	require.NoError(t, err)
	require.NotContains(t, got.Titles, titleId)

	var seasonCount int
	err = s.pool.QueryRow(ctx,
		`SELECT count(*) FROM group_title_seasons WHERE group_id = $1 AND title_id = $2`,
		created.Id, titleId).Scan(&seasonCount)
	require.NoError(t, err)
	require.Zero(t, seasonCount, "group_title_seasons must cascade-delete with their parent group_title")

	t.Run("non-member guard", func(t *testing.T) {
		err := s.RemoveTitleFromGroup(ctx, created.Id, titleId, "outsider")
		require.ErrorIs(t, err, store.ErrRecordNotFound)
	})
}

func TestStore_UpdateGroupInfo(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	created, err := s.CreateGroup(ctx, newTestGroup(t, "old name", owner))
	require.NoError(t, err)

	require.NoError(t, s.UpdateGroupInfo(ctx, created.Id, "new name", "a description"))

	got, err := s.GetGroupById(ctx, created.Id, owner)
	require.NoError(t, err)
	require.Equal(t, "new name", got.Name)
	require.Equal(t, "a description", got.Description)

	t.Run("missing group is not found", func(t *testing.T) {
		err := s.UpdateGroupInfo(ctx, "no-such-group", "x", "y")
		require.ErrorIs(t, err, store.ErrRecordNotFound)
	})
}

func TestStore_CreateGroup_DuplicateActiveName(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	first, err := s.CreateGroup(ctx, newTestGroup(t, "dupe", owner))
	require.NoError(t, err)

	// Same owner + same name while the first is active => duplicate.
	_, err = s.CreateGroup(ctx, newTestGroup(t, "dupe", owner))
	require.ErrorIs(t, err, store.ErrDuplicatedRecord)

	// UpdateGroupInfo into a taken active name is also a duplicate.
	other, err := s.CreateGroup(ctx, newTestGroup(t, "other", owner))
	require.NoError(t, err)
	err = s.UpdateGroupInfo(ctx, other.Id, "dupe", "")
	require.ErrorIs(t, err, store.ErrDuplicatedRecord)

	// After soft-deleting the first, the name is reusable (partial index only
	// covers non-deleted rows).
	require.NoError(t, s.SoftDeleteGroup(ctx, first.Id))
	reused, err := s.CreateGroup(ctx, newTestGroup(t, "dupe", owner))
	require.NoError(t, err)
	require.NotEmpty(t, reused.Id)
}

func TestStore_RemoveUserFromGroup(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	member := addTestUser(t, s)
	created, err := s.CreateGroup(ctx, newTestGroup(t, "leavers", owner))
	require.NoError(t, err)
	require.NoError(t, s.AddUserToGroup(ctx, created.Id, owner, member))

	require.NoError(t, s.RemoveUserFromGroup(ctx, created.Id, member))

	got, err := s.GetGroupById(ctx, created.Id, owner)
	require.NoError(t, err)
	require.NotContains(t, got.Users, member)
	require.Contains(t, got.Users, owner)

	// The removed member can no longer read the group.
	_, err = s.GetGroupById(ctx, created.Id, member)
	require.ErrorIs(t, err, store.ErrRecordNotFound)

	t.Run("missing/deleted group is not found", func(t *testing.T) {
		require.NoError(t, s.SoftDeleteGroup(ctx, created.Id))
		err := s.RemoveUserFromGroup(ctx, created.Id, owner)
		require.ErrorIs(t, err, store.ErrRecordNotFound)
	})
}

func TestStore_GroupExists(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	created, err := s.CreateGroup(ctx, newTestGroup(t, "exists", owner))
	require.NoError(t, err)

	ok, err := s.GroupExists(ctx, created.Id, owner)
	require.NoError(t, err)
	require.True(t, ok)

	ok, err = s.GroupExists(ctx, created.Id, "outsider")
	require.NoError(t, err)
	require.False(t, ok, "non-members must not see the group as existing")

	require.NoError(t, s.SoftDeleteGroup(ctx, created.Id))
	ok, err = s.GroupExists(ctx, created.Id, owner)
	require.NoError(t, err)
	require.False(t, ok, "a soft-deleted group must not exist")
}

func TestStore_GetGroupTitlesPage(t *testing.T) {
	t.Run("happy path: no filters, default order is alphabetical by primary_title; total equals group size", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		owner := addTestUser(t, s)
		group, err := s.CreateGroup(ctx, newTestGroup(t, "happy", owner))
		require.NoError(t, err)

		bravo := newTestMovieTitle(t, "tt-happy-bravo", "Bravo", 5.0)
		alpha := newTestMovieTitle(t, "tt-happy-alpha", "Alpha", 6.0)
		charlie := newTestMovieTitle(t, "tt-happy-charlie", "Charlie", 7.0)
		for _, ti := range []models.Title{bravo, alpha, charlie} {
			require.NoError(t, s.AddTitle(ctx, ti))
			require.NoError(t, s.AddNewGroupTitle(ctx, group.Id, ti.ID))
		}

		got, total, err := s.GetGroupTitlesPage(ctx, group.Id, nil, nil, "", nil, 10, 1)
		require.NoError(t, err)
		require.EqualValues(t, 3, total, "the window-function total must be present and correct on a full page")
		require.Len(t, got, 3)
		require.Equal(t, []string{"Alpha", "Bravo", "Charlie"},
			[]string{got[0].Title.PrimaryTitle, got[1].Title.PrimaryTitle, got[2].Title.PrimaryTitle})
		// Every row carries the full title plus the group's item for it.
		require.Equal(t, alpha.ID, got[0].Title.ID)
		require.Equal(t, alpha.ID, got[0].Item.TitleId)
	})

	t.Run("watched filter (true and false)", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		owner := addTestUser(t, s)
		group, err := s.CreateGroup(ctx, newTestGroup(t, "watched-filter", owner))
		require.NoError(t, err)

		watchedTitle := newTestMovieTitle(t, "tt-watched", "Watched One", 5.0)
		unwatchedTitle := newTestMovieTitle(t, "tt-unwatched", "Unwatched One", 5.0)
		require.NoError(t, s.AddTitle(ctx, watchedTitle))
		require.NoError(t, s.AddTitle(ctx, unwatchedTitle))

		now := time.Now().UTC().Truncate(time.Second)
		addGroupTitleRow(t, s, group.Id, watchedTitle.ID, "movie", true, &now, now, now)
		addGroupTitleRow(t, s, group.Id, unwatchedTitle.ID, "movie", false, nil, now, now)

		got, total, err := s.GetGroupTitlesPage(ctx, group.Id, boolPtr(true), nil, "", nil, 10, 1)
		require.NoError(t, err)
		require.EqualValues(t, 1, total)
		require.Len(t, got, 1)
		require.Equal(t, watchedTitle.ID, got[0].Title.ID)
		require.True(t, got[0].Item.Watched)

		got, total, err = s.GetGroupTitlesPage(ctx, group.Id, boolPtr(false), nil, "", nil, 10, 1)
		require.NoError(t, err)
		require.EqualValues(t, 1, total)
		require.Len(t, got, 1)
		require.Equal(t, unwatchedTitle.ID, got[0].Title.ID)
		require.False(t, got[0].Item.Watched)
	})

	t.Run("titleTypes filter (single and multi-element)", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		owner := addTestUser(t, s)
		group, err := s.CreateGroup(ctx, newTestGroup(t, "types", owner))
		require.NoError(t, err)

		movie := addTestTitleWithType(t, s, "tt-type-movie", "A Movie", "movie")
		series := addTestTitleWithType(t, s, "tt-type-series", "A Series", "tvSeries")
		short := addTestTitleWithType(t, s, "tt-type-short", "A Short", "short")

		now := time.Now().UTC().Truncate(time.Second)
		for _, ti := range []models.Title{movie, series, short} {
			addGroupTitleRow(t, s, group.Id, ti.ID, ti.Type, false, nil, now, now)
		}

		got, total, err := s.GetGroupTitlesPage(ctx, group.Id, nil, []string{"movie"}, "", nil, 10, 1)
		require.NoError(t, err)
		require.EqualValues(t, 1, total)
		require.Len(t, got, 1)
		require.Equal(t, movie.ID, got[0].Title.ID)

		got, total, err = s.GetGroupTitlesPage(ctx, group.Id, nil, []string{"movie", "tvSeries"}, "", nil, 10, 1)
		require.NoError(t, err)
		require.EqualValues(t, 2, total)
		require.Len(t, got, 2)
		require.ElementsMatch(t, []string{movie.ID, series.ID}, []string{got[0].Title.ID, got[1].Title.ID})
	})

	t.Run("watched and titleTypes filters combined", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		owner := addTestUser(t, s)
		group, err := s.CreateGroup(ctx, newTestGroup(t, "combined", owner))
		require.NoError(t, err)

		movieWatched := addTestTitleWithType(t, s, "tt-c-movie-w", "Movie Watched", "movie")
		movieUnwatched := addTestTitleWithType(t, s, "tt-c-movie-u", "Movie Unwatched", "movie")
		seriesWatched := addTestTitleWithType(t, s, "tt-c-series-w", "Series Watched", "tvSeries")

		now := time.Now().UTC().Truncate(time.Second)
		addGroupTitleRow(t, s, group.Id, movieWatched.ID, "movie", true, &now, now, now)
		addGroupTitleRow(t, s, group.Id, movieUnwatched.ID, "movie", false, nil, now, now)
		addGroupTitleRow(t, s, group.Id, seriesWatched.ID, "tvSeries", true, &now, now, now)

		got, total, err := s.GetGroupTitlesPage(ctx, group.Id, boolPtr(true), []string{"movie"}, "", nil, 10, 1)
		require.NoError(t, err)
		require.EqualValues(t, 1, total)
		require.Len(t, got, 1)
		require.Equal(t, movieWatched.ID, got[0].Title.ID)
	})

	t.Run("sort by imdbRating ascending", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		owner := addTestUser(t, s)
		group, err := s.CreateGroup(ctx, newTestGroup(t, "rating-sort", owner))
		require.NoError(t, err)

		// ids are deliberately reversed relative to the expected rating order,
		// so a correct result can only come from sorting by rating_aggregate,
		// never by falling back to the id tie-break.
		low := newTestMovieTitle(t, "tt-z-low-rating", "Z Low", 3.0)
		high := newTestMovieTitle(t, "tt-a-high-rating", "A High", 9.0)
		require.NoError(t, s.AddTitle(ctx, low))
		require.NoError(t, s.AddTitle(ctx, high))
		now := time.Now().UTC().Truncate(time.Second)
		addGroupTitleRow(t, s, group.Id, low.ID, "movie", false, nil, now, now)
		addGroupTitleRow(t, s, group.Id, high.ID, "movie", false, nil, now, now)

		got, _, err := s.GetGroupTitlesPage(ctx, group.Id, nil, nil, "imdbRating", nil, 10, 1)
		require.NoError(t, err)
		require.Equal(t, []string{low.ID, high.ID}, []string{got[0].Title.ID, got[1].Title.ID})
	})

	t.Run("sort by startYear ascending", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		owner := addTestUser(t, s)
		group, err := s.CreateGroup(ctx, newTestGroup(t, "year-sort", owner))
		require.NoError(t, err)

		early := newTestMovieTitle(t, "tt-z-early-year", "Z Early", 5.0)
		early.StartYear = 1990
		late := newTestMovieTitle(t, "tt-a-late-year", "A Late", 5.0)
		late.StartYear = 2020
		require.NoError(t, s.AddTitle(ctx, early))
		require.NoError(t, s.AddTitle(ctx, late))
		now := time.Now().UTC().Truncate(time.Second)
		addGroupTitleRow(t, s, group.Id, early.ID, "movie", false, nil, now, now)
		addGroupTitleRow(t, s, group.Id, late.ID, "movie", false, nil, now, now)

		got, _, err := s.GetGroupTitlesPage(ctx, group.Id, nil, nil, "startYear", nil, 10, 1)
		require.NoError(t, err)
		require.Equal(t, []string{early.ID, late.ID}, []string{got[0].Title.ID, got[1].Title.ID})
	})

	t.Run("sort by type ascending", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		owner := addTestUser(t, s)
		group, err := s.CreateGroup(ctx, newTestGroup(t, "type-sort", owner))
		require.NoError(t, err)

		movieT := addTestTitleWithType(t, s, "tt-z-movie-type", "Z Movie", "movie")
		seriesT := addTestTitleWithType(t, s, "tt-a-series-type", "A Series", "tvSeries")
		now := time.Now().UTC().Truncate(time.Second)
		addGroupTitleRow(t, s, group.Id, movieT.ID, "movie", false, nil, now, now)
		addGroupTitleRow(t, s, group.Id, seriesT.ID, "tvSeries", false, nil, now, now)

		got, _, err := s.GetGroupTitlesPage(ctx, group.Id, nil, nil, "type", nil, 10, 1)
		require.NoError(t, err)
		require.Equal(t, []string{movieT.ID, seriesT.ID}, []string{got[0].Title.ID, got[1].Title.ID},
			`"movie" sorts before "tvSeries" lexically`)
	})

	t.Run("sort by voteCount ascending", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		owner := addTestUser(t, s)
		group, err := s.CreateGroup(ctx, newTestGroup(t, "votecount-sort", owner))
		require.NoError(t, err)

		few := newTestMovieTitle(t, "tt-z-few-votes", "Z Few", 5.0)
		few.Rating.VoteCount = 10
		many := newTestMovieTitle(t, "tt-a-many-votes", "A Many", 5.0)
		many.Rating.VoteCount = 100000
		require.NoError(t, s.AddTitle(ctx, few))
		require.NoError(t, s.AddTitle(ctx, many))
		now := time.Now().UTC().Truncate(time.Second)
		addGroupTitleRow(t, s, group.Id, few.ID, "movie", false, nil, now, now)
		addGroupTitleRow(t, s, group.Id, many.ID, "movie", false, nil, now, now)

		got, _, err := s.GetGroupTitlesPage(ctx, group.Id, nil, nil, "voteCount", nil, 10, 1)
		require.NoError(t, err)
		require.Equal(t, []string{few.ID, many.ID}, []string{got[0].Title.ID, got[1].Title.ID})
	})

	t.Run("sort by updatedAt descending keeps titles' default NULL placement (NULLS FIRST)", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		owner := addTestUser(t, s)
		group, err := s.CreateGroup(ctx, newTestGroup(t, "updatedat-sort", owner))
		require.NoError(t, err)

		dated := newTestMovieTitle(t, "tt-dated-updated", "Dated", 5.0) // UpdatedAt = now, set by the fixture.
		nullUpdated := newTestMovieTitle(t, "tt-null-updated", "NullUpdated", 5.0)
		nullUpdated.UpdatedAt = nil
		require.NoError(t, s.AddTitle(ctx, dated))
		require.NoError(t, s.AddTitle(ctx, nullUpdated))
		now := time.Now().UTC().Truncate(time.Second)
		addGroupTitleRow(t, s, group.Id, dated.ID, "movie", false, nil, now, now)
		addGroupTitleRow(t, s, group.Id, nullUpdated.ID, "movie", false, nil, now, now)

		descending := false // ascending=false means descending, per the store's contract
		got, _, err := s.GetGroupTitlesPage(ctx, group.Id, nil, nil, "updatedAt", &descending, 10, 1)
		require.NoError(t, err)
		require.Equal(t, []string{nullUpdated.ID, dated.ID}, []string{got[0].Title.ID, got[1].Title.ID},
			"unlike watchedAt, updatedAt carries no explicit NULLS clause, so Postgres' DESC default (NULLS FIRST) decides")
	})

	t.Run("sort by addedAt ascending", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		owner := addTestUser(t, s)
		group, err := s.CreateGroup(ctx, newTestGroup(t, "addedat-sort", owner))
		require.NoError(t, err)

		older := newTestMovieTitle(t, "tt-z-older-added", "Z Older", 5.0)
		newer := newTestMovieTitle(t, "tt-a-newer-added", "A Newer", 5.0)
		require.NoError(t, s.AddTitle(ctx, older))
		require.NoError(t, s.AddTitle(ctx, newer))
		now := time.Now().UTC().Truncate(time.Second)
		addGroupTitleRow(t, s, group.Id, older.ID, "movie", false, nil, now.Add(-48*time.Hour), now)
		addGroupTitleRow(t, s, group.Id, newer.ID, "movie", false, nil, now, now)

		got, _, err := s.GetGroupTitlesPage(ctx, group.Id, nil, nil, "addedAt", nil, 10, 1)
		require.NoError(t, err)
		require.Equal(t, []string{older.ID, newer.ID}, []string{got[0].Title.ID, got[1].Title.ID})
	})

	t.Run("sort by watched, both directions", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		owner := addTestUser(t, s)
		group, err := s.CreateGroup(ctx, newTestGroup(t, "watched-sort", owner))
		require.NoError(t, err)

		watchedTitle := newTestMovieTitle(t, "tt-z-watched-sort", "Z Watched", 5.0)
		unwatchedTitle := newTestMovieTitle(t, "tt-a-unwatched-sort", "A Unwatched", 5.0)
		require.NoError(t, s.AddTitle(ctx, watchedTitle))
		require.NoError(t, s.AddTitle(ctx, unwatchedTitle))
		now := time.Now().UTC().Truncate(time.Second)
		addGroupTitleRow(t, s, group.Id, watchedTitle.ID, "movie", true, &now, now, now)
		addGroupTitleRow(t, s, group.Id, unwatchedTitle.ID, "movie", false, nil, now, now)

		got, _, err := s.GetGroupTitlesPage(ctx, group.Id, nil, nil, "watched", nil, 10, 1)
		require.NoError(t, err)
		require.Equal(t, []string{unwatchedTitle.ID, watchedTitle.ID}, []string{got[0].Title.ID, got[1].Title.ID},
			"ascending: false sorts before true")

		descending := false // ascending=false means descending, per the store's contract
		got, _, err = s.GetGroupTitlesPage(ctx, group.Id, nil, nil, "watched", &descending, 10, 1)
		require.NoError(t, err)
		require.Equal(t, []string{watchedTitle.ID, unwatchedTitle.ID}, []string{got[0].Title.ID, got[1].Title.ID},
			"descending: true sorts before false")
	})

	t.Run("sort by watchedAt, both directions, nil watchedAt lands last either way", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		owner := addTestUser(t, s)
		group, err := s.CreateGroup(ctx, newTestGroup(t, "watchedat-sort", owner))
		require.NoError(t, err)

		earlyWatched := newTestMovieTitle(t, "tt-early-watched", "Early Watched", 5.0)
		lateWatched := newTestMovieTitle(t, "tt-late-watched", "Late Watched", 5.0)
		neverWatched := newTestMovieTitle(t, "tt-never-watched", "Never Watched", 5.0)
		for _, ti := range []models.Title{earlyWatched, lateWatched, neverWatched} {
			require.NoError(t, s.AddTitle(ctx, ti))
		}

		now := time.Now().UTC().Truncate(time.Second)
		early := now.Add(-48 * time.Hour)
		late := now
		addGroupTitleRow(t, s, group.Id, earlyWatched.ID, "movie", true, &early, now, now)
		addGroupTitleRow(t, s, group.Id, lateWatched.ID, "movie", true, &late, now, now)
		addGroupTitleRow(t, s, group.Id, neverWatched.ID, "movie", false, nil, now, now)

		got, _, err := s.GetGroupTitlesPage(ctx, group.Id, nil, nil, "watchedAt", nil, 10, 1)
		require.NoError(t, err)
		require.Equal(t, []string{earlyWatched.ID, lateWatched.ID, neverWatched.ID},
			[]string{got[0].Title.ID, got[1].Title.ID, got[2].Title.ID},
			"ascending: earliest watchedAt first, nil last")

		descending := false // ascending=false means descending, per the store's contract
		got, _, err = s.GetGroupTitlesPage(ctx, group.Id, nil, nil, "watchedAt", &descending, 10, 1)
		require.NoError(t, err)
		require.Equal(t, []string{lateWatched.ID, earlyWatched.ID, neverWatched.ID},
			[]string{got[0].Title.ID, got[1].Title.ID, got[2].Title.ID},
			"descending: latest watchedAt first, nil still last")
	})

	t.Run("unknown orderBy falls back to primaryTitle, keeping the requested direction", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		owner := addTestUser(t, s)
		group, err := s.CreateGroup(ctx, newTestGroup(t, "fallback", owner))
		require.NoError(t, err)

		alpha := newTestMovieTitle(t, "tt-fb-alpha", "Alpha", 5.0)
		bravo := newTestMovieTitle(t, "tt-fb-bravo", "Bravo", 5.0)
		charlie := newTestMovieTitle(t, "tt-fb-charlie", "Charlie", 5.0)
		for _, ti := range []models.Title{alpha, bravo, charlie} {
			require.NoError(t, s.AddTitle(ctx, ti))
			require.NoError(t, s.AddNewGroupTitle(ctx, group.Id, ti.ID))
		}

		descending := false // ascending=false means descending, per the store's contract
		got, total, err := s.GetGroupTitlesPage(ctx, group.Id, nil, nil, "garbage", &descending, 10, 1)
		require.NoError(t, err)
		require.EqualValues(t, 3, total)
		require.Equal(t, []string{"Charlie", "Bravo", "Alpha"},
			[]string{got[0].Title.PrimaryTitle, got[1].Title.PrimaryTitle, got[2].Title.PrimaryTitle})
	})

	t.Run("pagination partitions exactly; an out-of-range page returns empty content with the correct total", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		owner := addTestUser(t, s)
		group, err := s.CreateGroup(ctx, newTestGroup(t, "paging", owner))
		require.NoError(t, err)

		names := []string{"Alpha", "Bravo", "Charlie", "Delta", "Echo"}
		for i, name := range names {
			title := newTestMovieTitle(t, fmt.Sprintf("tt-page-%d", i), name, 5.0)
			require.NoError(t, s.AddTitle(ctx, title))
			require.NoError(t, s.AddNewGroupTitle(ctx, group.Id, title.ID))
		}

		var got []string
		for page := 1; page <= 3; page++ {
			titles, total, err := s.GetGroupTitlesPage(ctx, group.Id, nil, nil, "", nil, 2, page)
			require.NoError(t, err)
			require.EqualValues(t, 5, total, "the total must not move while paging")
			for _, ti := range titles {
				got = append(got, ti.Title.PrimaryTitle)
			}
		}
		require.Equal(t, names, got, "pages must partition the sorted set exactly, with no duplicate or skipped row")

		empty, total, err := s.GetGroupTitlesPage(ctx, group.Id, nil, nil, "", nil, 2, 4)
		require.NoError(t, err)
		require.Empty(t, empty)
		require.EqualValues(t, 5, total, "an out-of-range page must still report the correct total")
	})

	t.Run("an extreme page number returns an empty page with the correct total instead of erroring", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		owner := addTestUser(t, s)
		group, err := s.CreateGroup(ctx, newTestGroup(t, "extreme-page", owner))
		require.NoError(t, err)

		names := []string{"Alpha", "Bravo", "Charlie"}
		for i, name := range names {
			title := newTestMovieTitle(t, fmt.Sprintf("tt-extreme-%d", i), name, 5.0)
			require.NoError(t, s.AddTitle(ctx, title))
			require.NoError(t, s.AddNewGroupTitle(ctx, group.Id, title.ID))
		}

		cases := []struct {
			name string
			page int
		}{
			// (page-1)*size = 2_999_999_900, past the end of any real table
			// and past int32 — it reaches Postgres as a bigint OFFSET and
			// must come back as an empty page, not as the "OFFSET must not
			// be negative" 500 a narrowing cast used to produce.
			{"exceeds int32 but not int64", 30_000_000},
			// page-1 is near MaxInt64; multiplying by size=100 in int64
			// BEFORE the overflow guard would itself wrap to a small
			// negative int64 (offset -200), reintroducing the original
			// "OFFSET must not be negative" 500. The guard must reject this
			// by comparing before any multiply, not after.
			{"page-1 near MaxInt64: int64 multiply would wrap negative", math.MaxInt64},
			// page-1 * size wraps to a small POSITIVE int64 (92) if the
			// guard multiplies first — which would silently return some
			// unrelated page's rows instead of erroring or emptying out.
			{"page-1 * size wraps to a small positive int64", 92_233_720_368_547_760},
		}
		for _, tc := range cases {
			t.Run(tc.name, func(t *testing.T) {
				got, total, err := s.GetGroupTitlesPage(ctx, group.Id, nil, nil, "", nil, 100, tc.page)
				require.NoError(t, err)
				require.Equal(t, []models.GroupPagedTitle{}, got)
				require.EqualValues(t, len(names), total)
			})
		}
	})

	// Clamping size is the service's job, so it arrives here unvalidated, and
	// this method is reachable directly (this file). A non-positive size must
	// page to nothing, the way it did when size was only ever bound as a
	// LIMIT parameter. size == 0 in particular must never reach the offset
	// guard's division by size: this process has no panic-recovery
	// middleware, so an integer divide-by-zero there takes the whole server
	// down rather than failing one request.
	t.Run("a non-positive size returns an empty page with the correct total", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		owner := addTestUser(t, s)
		group, err := s.CreateGroup(ctx, newTestGroup(t, "non-positive-size", owner))
		require.NoError(t, err)

		names := []string{"Alpha", "Bravo", "Charlie"}
		for i, name := range names {
			title := newTestMovieTitle(t, fmt.Sprintf("tt-size-%d", i), name, 5.0)
			require.NoError(t, s.AddTitle(ctx, title))
			require.NoError(t, s.AddNewGroupTitle(ctx, group.Id, title.ID))
		}

		for _, size := range []int{0, -1, math.MinInt64} {
			t.Run(fmt.Sprintf("size=%d", size), func(t *testing.T) {
				for _, page := range []int{1, 2, math.MaxInt64} {
					// Asserted through NotPanics rather than called directly:
					// without the guard this is an integer divide-by-zero, and
					// an unrecovered panic aborts the whole test binary instead
					// of reporting which case regressed.
					var (
						got   []models.GroupPagedTitle
						total int64
						err   error
					)
					require.NotPanics(t, func() {
						got, total, err = s.GetGroupTitlesPage(ctx, group.Id, nil, nil, "", nil, size, page)
					}, "size=%d page=%d must not panic", size, page)
					require.NoError(t, err, "size=%d page=%d must not error", size, page)
					require.Equal(t, []models.GroupPagedTitle{}, got, "size=%d page=%d must page to nothing", size, page)
					require.EqualValues(t, len(names), total, "size=%d page=%d must still report the real total", size, page)
				}
			})
		}
	})

	// MAX_PAGE_SIZE is env-configurable with no upper bound, so the clamped
	// size the service passes down can legitimately exceed int32. Narrowing it
	// to the generated LIMIT parameter used to wrap it negative, and Postgres
	// rejects a negative LIMIT outright — every request would 500. page_size
	// is a bigint for exactly this reason.
	t.Run("a size larger than int32 is not narrowed", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		owner := addTestUser(t, s)
		group, err := s.CreateGroup(ctx, newTestGroup(t, "wide-size", owner))
		require.NoError(t, err)

		names := []string{"Alpha", "Bravo", "Charlie"}
		for i, name := range names {
			title := newTestMovieTitle(t, fmt.Sprintf("tt-wide-%d", i), name, 5.0)
			require.NoError(t, s.AddTitle(ctx, title))
			require.NoError(t, s.AddNewGroupTitle(ctx, group.Id, title.ID))
		}

		got, total, err := s.GetGroupTitlesPage(ctx, group.Id, nil, nil, "", nil, math.MaxInt32+1, 1)
		require.NoError(t, err, "a size past int32 must not wrap into a negative LIMIT")
		require.Len(t, got, len(names), "a size that large must simply return every row")
		require.EqualValues(t, len(names), total)
	})

	t.Run("a group_titles row with no matching titles row is invisible to content and total", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		owner := addTestUser(t, s)
		group, err := s.CreateGroup(ctx, newTestGroup(t, "orphan", owner))
		require.NoError(t, err)

		present := newTestMovieTitle(t, "tt-present", "Present", 5.0)
		require.NoError(t, s.AddTitle(ctx, present))
		require.NoError(t, s.AddNewGroupTitle(ctx, group.Id, present.ID))

		// group_titles.title_id carries no FK to titles, so this row can exist
		// with no backing titles row. The INNER JOIN in GetGroupTitlesPage must
		// hide it from both content and total.
		now := time.Now().UTC().Truncate(time.Second)
		addGroupTitleRow(t, s, group.Id, "tt-missing-title", "movie", false, nil, now, now)

		got, total, err := s.GetGroupTitlesPage(ctx, group.Id, nil, nil, "", nil, 10, 1)
		require.NoError(t, err)
		require.EqualValues(t, 1, total)
		require.Len(t, got, 1)
		require.Equal(t, present.ID, got[0].Title.ID)
	})

	// group_titles.title_type and titles.type are independent stores of the
	// same fact, and they disagree constantly: AddNewGroupTitle stamps the
	// literal "movie" on every entry and nothing ever refreshes it, so on the
	// production database 98 of 122 rows carry a title_type that contradicts
	// the catalogue. This page reads the catalogue, deliberately — the same
	// column it filters titleType on, so a returned row can never claim a type
	// that its own filter would have excluded.
	t.Run("TitleType comes from the catalogue, not from the stale group_titles column", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		owner := addTestUser(t, s)
		group, err := s.CreateGroup(ctx, newTestGroup(t, "title-type-source", owner))
		require.NoError(t, err)

		series := newTestMovieTitle(t, "tt-type-source", "A Series", 5.0)
		series.Type = "tvSeries"
		require.NoError(t, s.AddTitle(ctx, series))

		// What AddNewGroupTitle would have written: "movie", now stale.
		now := time.Now().UTC().Truncate(time.Second)
		addGroupTitleRow(t, s, group.Id, series.ID, "movie", false, nil, now, now)

		got, _, err := s.GetGroupTitlesPage(ctx, group.Id, nil, nil, "", nil, 10, 1)
		require.NoError(t, err)
		require.Len(t, got, 1)
		require.Equal(t, "tvSeries", got[0].Item.TitleType,
			"the paged item must report the catalogue's type, not the stale group_titles.title_type")
		require.Equal(t, "tvSeries", got[0].Title.Type,
			"the item's type must agree with the title it was joined to")

		// And the filter agrees with what the row reports: asking for movies
		// excludes it entirely.
		movies, total, err := s.GetGroupTitlesPage(ctx, group.Id, nil, []string{"movie"}, "", nil, 10, 1)
		require.NoError(t, err)
		require.Empty(t, movies, "a titleType=movie filter must not return a title the catalogue calls a series")
		require.EqualValues(t, 0, total)
	})

	t.Run("seasons stitching: a series gets non-nil SeasonsWatched, a movie gets nil", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		owner := addTestUser(t, s)
		group, err := s.CreateGroup(ctx, newTestGroup(t, "seasons", owner))
		require.NoError(t, err)

		series := newTestMovieTitle(t, "tt-series-seasons", "A Series", 5.0)
		series.Type = "tvSeries"
		movie := newTestMovieTitle(t, "tt-movie-seasons", "A Movie", 5.0)
		require.NoError(t, s.AddTitle(ctx, series))
		require.NoError(t, s.AddTitle(ctx, movie))

		now := time.Now().UTC().Truncate(time.Second)
		addGroupTitleRow(t, s, group.Id, series.ID, "tvSeries", true, &now, now, now)
		addGroupTitleRow(t, s, group.Id, movie.ID, "movie", false, nil, now, now)
		addGroupTitleSeasonRow(t, s, group.Id, series.ID, "1", true, &now, now, now)
		addGroupTitleSeasonRow(t, s, group.Id, series.ID, "2", false, nil, now, now)

		got, _, err := s.GetGroupTitlesPage(ctx, group.Id, nil, nil, "", nil, 10, 1)
		require.NoError(t, err)
		require.Len(t, got, 2)

		byID := make(map[string]models.GroupPagedTitle, len(got))
		for _, item := range got {
			byID[item.Title.ID] = item
		}
		require.NotNil(t, byID[series.ID].Item.SeasonsWatched)
		require.Len(t, *byID[series.ID].Item.SeasonsWatched, 2)
		require.Nil(t, byID[movie.ID].Item.SeasonsWatched)
	})

	t.Run("empty group returns an empty slice and total 0", func(t *testing.T) {
		resetDB(t)
		s := newTestStore(t)
		ctx := context.Background()

		owner := addTestUser(t, s)
		group, err := s.CreateGroup(ctx, newTestGroup(t, "empty", owner))
		require.NoError(t, err)

		got, total, err := s.GetGroupTitlesPage(ctx, group.Id, nil, nil, "", nil, 10, 1)
		require.NoError(t, err)
		require.Equal(t, []models.GroupPagedTitle{}, got)
		require.EqualValues(t, 0, total)
	})
}
