package postgres

import (
	"context"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/stretchr/testify/require"

	"github.com/lealre/movies-backend/internal/generics"
	"github.com/lealre/movies-backend/internal/models"
	"github.com/lealre/movies-backend/internal/store"
)

// newTestGroup builds the minimal models.Group the service layer passes to
// Store.CreateGroup: owner-only Users slice, empty (non-nil) Titles map, and
// no Id/timestamps (those are generated by the store).
func newTestGroup(t *testing.T, name, ownerId string) models.Group {
	t.Helper()
	return models.Group{
		Name:        name,
		Description: "",
		OwnerId:     ownerId,
		Users:       []string{ownerId},
		Titles:      models.GroupTitles{},
	}
}

// addTestUser inserts and returns a fresh user id, so membership rows point at
// real users (needed for GetUsersFromGroup's JOIN and the member's own Groups).
func addTestUser(t *testing.T, s *Store) string {
	t.Helper()
	u := newTestUser(t)
	require.NoError(t, s.AddUser(context.Background(), u))
	return u.Id
}

func flexDate(tm time.Time) *generics.FlexibleDate {
	return &generics.FlexibleDate{Time: &tm}
}

func boolPtr(b bool) *bool { return &b }

func TestStore_CreateGroup_GetGroupById(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	created, err := s.CreateGroup(ctx, newTestGroup(t, "movie night", owner))
	require.NoError(t, err)
	require.NotEmpty(t, created.Id, "CreateGroup must generate an id")
	require.Equal(t, "movie night", created.Name)
	require.Equal(t, owner, created.OwnerId)
	require.Equal(t, []string{owner}, created.Users)
	require.NotNil(t, created.Titles, "Titles must be a non-nil (empty) map")
	require.Empty(t, created.Titles)
	require.False(t, created.Deleted)
	require.WithinDuration(t, time.Now(), created.CreatedAt, 5*time.Second)

	got, err := s.GetGroupById(ctx, created.Id, owner)
	require.NoError(t, err)
	require.Equal(t, created.Id, got.Id)
	require.Equal(t, "movie night", got.Name)
	require.Contains(t, got.Users, owner, "owner must be auto-added as a member")
	require.NotNil(t, got.Titles)
	require.Empty(t, got.Titles)
}

func TestStore_GetGroupById_NonMember(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	created, err := s.CreateGroup(ctx, newTestGroup(t, "private", owner))
	require.NoError(t, err)

	_, err = s.GetGroupById(ctx, created.Id, "outsider")
	require.ErrorIs(t, err, store.ErrRecordNotFound)
}

func TestStore_GetGroupById_SoftDeleted(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	created, err := s.CreateGroup(ctx, newTestGroup(t, "temp", owner))
	require.NoError(t, err)

	require.NoError(t, s.SoftDeleteGroup(ctx, created.Id))

	_, err = s.GetGroupById(ctx, created.Id, owner)
	require.ErrorIs(t, err, store.ErrRecordNotFound, "a soft-deleted group must not be found")

	// SoftDeleteGroup is idempotent-guarded: deleting again reports not found.
	err = s.SoftDeleteGroup(ctx, created.Id)
	require.ErrorIs(t, err, store.ErrRecordNotFound)
}

func TestStore_AddUserToGroup(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	member := addTestUser(t, s)
	created, err := s.CreateGroup(ctx, newTestGroup(t, "crew", owner))
	require.NoError(t, err)

	require.NoError(t, s.AddUserToGroup(ctx, created.Id, owner, member))

	got, err := s.GetGroupById(ctx, created.Id, member)
	require.NoError(t, err)
	require.Contains(t, got.Users, owner)
	require.Contains(t, got.Users, member)
	require.Len(t, got.Users, 2)

	// The new member's own user Groups must now include this group.
	memberUser, err := s.GetUserById(ctx, member)
	require.NoError(t, err)
	require.Contains(t, memberUser.Groups, created.Id)

	t.Run("non-owner guard reports not found", func(t *testing.T) {
		err := s.AddUserToGroup(ctx, created.Id, "not-a-member", "someone")
		require.ErrorIs(t, err, store.ErrRecordNotFound)
	})
}

func TestStore_GetUsersFromGroup(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	member := addTestUser(t, s)
	created, err := s.CreateGroup(ctx, newTestGroup(t, "watch club", owner))
	require.NoError(t, err)
	require.NoError(t, s.AddUserToGroup(ctx, created.Id, owner, member))

	users, err := s.GetUsersFromGroup(ctx, created.Id, owner)
	require.NoError(t, err)
	require.Len(t, users, 2)

	ids := []string{users[0].Id, users[1].Id}
	require.ElementsMatch(t, []string{owner, member}, ids)
	for _, u := range users {
		require.Contains(t, u.Groups, created.Id, "each member's Groups must include the group")
	}

	t.Run("non-member is refused", func(t *testing.T) {
		_, err := s.GetUsersFromGroup(ctx, created.Id, "outsider")
		require.ErrorIs(t, err, store.ErrRecordNotFound)
	})
}

func TestStore_AddNewGroupTitle(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	created, err := s.CreateGroup(ctx, newTestGroup(t, "queue", owner))
	require.NoError(t, err)

	titleId := "tt-" + uuid.NewString()
	require.NoError(t, s.AddNewGroupTitle(ctx, created.Id, titleId))

	got, err := s.GetGroupById(ctx, created.Id, owner)
	require.NoError(t, err)
	require.Contains(t, got.Titles, titleId)
	item := got.Titles[titleId]
	require.Equal(t, titleId, item.TitleId)
	require.Equal(t, "movie", item.TitleType)
	require.False(t, item.Watched)
	require.Nil(t, item.SeasonsWatched, "a freshly added movie must have nil SeasonsWatched")
	require.Nil(t, item.WatchedAt)

	// GroupContainsTitle reflects the new title; a bogus title does not.
	contains, err := s.GroupContainsTitle(ctx, created.Id, titleId, owner)
	require.NoError(t, err)
	require.True(t, contains)
	contains, err = s.GroupContainsTitle(ctx, created.Id, "tt-nope", owner)
	require.NoError(t, err)
	require.False(t, contains)
}

func TestStore_UpdateGroupTitleWatchedForMovie(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	created, err := s.CreateGroup(ctx, newTestGroup(t, "movies", owner))
	require.NoError(t, err)
	titleId := "tt-" + uuid.NewString()
	require.NoError(t, s.AddNewGroupTitle(ctx, created.Id, titleId))

	when := time.Now().UTC().Truncate(time.Second)
	item, err := s.UpdateGroupTitleWatchedForMovie(ctx, created.Id, titleId, boolPtr(true), flexDate(when))
	require.NoError(t, err)
	require.NotNil(t, item)
	require.True(t, item.Watched)
	require.NotNil(t, item.WatchedAt)
	require.WithinDuration(t, when, *item.WatchedAt, time.Second)
	require.Nil(t, item.SeasonsWatched)

	// Persisted: re-read shows watched.
	got, err := s.GetGroupById(ctx, created.Id, owner)
	require.NoError(t, err)
	require.True(t, got.Titles[titleId].Watched)

	t.Run("watched=false clears watchedAt when cleared by caller", func(t *testing.T) {
		// The service passes a nil-Time FlexibleDate to clear watchedAt.
		item, err := s.UpdateGroupTitleWatchedForMovie(ctx, created.Id, titleId, boolPtr(false), &generics.FlexibleDate{Time: nil})
		require.NoError(t, err)
		require.False(t, item.Watched)
		require.Nil(t, item.WatchedAt, "watchedAt must be cleared to nil")
	})

	t.Run("no fields to update is an error", func(t *testing.T) {
		_, err := s.UpdateGroupTitleWatchedForMovie(ctx, created.Id, titleId, nil, nil)
		require.Error(t, err)
	})

	t.Run("missing title is not found", func(t *testing.T) {
		_, err := s.UpdateGroupTitleWatchedForMovie(ctx, created.Id, "tt-missing", boolPtr(true), nil)
		require.ErrorIs(t, err, store.ErrRecordNotFound)
	})
}

func TestStore_UpdateGroupTitleWatchedForTVSeries(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	created, err := s.CreateGroup(ctx, newTestGroup(t, "series", owner))
	require.NoError(t, err)
	titleId := "tt-" + uuid.NewString()
	require.NoError(t, s.AddNewGroupTitle(ctx, created.Id, titleId))

	when1 := time.Now().UTC().Truncate(time.Second)

	// Mark season 1 watched: top-level watched becomes true (at least one
	// season watched) and top-level watchedAt is season 1's date.
	item, err := s.UpdateGroupTitleWatchedForTVSeries(ctx, created.Id, titleId, boolPtr(true), flexDate(when1), 1, owner)
	require.NoError(t, err)
	require.NotNil(t, item)
	require.NotNil(t, item.SeasonsWatched, "SeasonsWatched must become a non-nil map")
	require.Contains(t, *item.SeasonsWatched, "1")
	require.True(t, (*item.SeasonsWatched)["1"].Watched)
	require.True(t, item.Watched, "top-level watched must be true when >=1 season is watched")
	require.NotNil(t, item.WatchedAt)
	require.WithinDuration(t, when1, *item.WatchedAt, time.Second)

	// Add season 2 with a LATER date: top-level watchedAt must move to the max.
	when2 := when1.Add(48 * time.Hour)
	item, err = s.UpdateGroupTitleWatchedForTVSeries(ctx, created.Id, titleId, boolPtr(true), flexDate(when2), 2, owner)
	require.NoError(t, err)
	require.Len(t, *item.SeasonsWatched, 2)
	require.True(t, item.Watched)
	require.WithinDuration(t, when2, *item.WatchedAt, time.Second, "top-level watchedAt must be the latest watched season's date")

	// Un-watch season 2 (service clears its watchedAt): season 1 still watched,
	// so top-level stays watched with season 1's earlier date.
	item, err = s.UpdateGroupTitleWatchedForTVSeries(ctx, created.Id, titleId, boolPtr(false), &generics.FlexibleDate{Time: nil}, 2, owner)
	require.NoError(t, err)
	require.False(t, (*item.SeasonsWatched)["2"].Watched)
	require.Nil(t, (*item.SeasonsWatched)["2"].WatchedAt)
	require.True(t, item.Watched, "still watched because season 1 remains watched")
	require.WithinDuration(t, when1, *item.WatchedAt, time.Second)

	// Un-watch season 1 too: no season watched => top-level watched=false,
	// watchedAt=nil.
	item, err = s.UpdateGroupTitleWatchedForTVSeries(ctx, created.Id, titleId, boolPtr(false), &generics.FlexibleDate{Time: nil}, 1, owner)
	require.NoError(t, err)
	require.False(t, item.Watched, "no watched seasons => top-level watched=false")
	require.Nil(t, item.WatchedAt, "no watched seasons => top-level watchedAt=nil")

	// The whole thing persists across a fresh read.
	got, err := s.GetGroupById(ctx, created.Id, owner)
	require.NoError(t, err)
	gt := got.Titles[titleId]
	require.NotNil(t, gt.SeasonsWatched)
	require.Len(t, *gt.SeasonsWatched, 2)
	require.False(t, gt.Watched)

	t.Run("non-member guard", func(t *testing.T) {
		_, err := s.UpdateGroupTitleWatchedForTVSeries(ctx, created.Id, titleId, boolPtr(true), nil, 1, "outsider")
		require.ErrorIs(t, err, store.ErrRecordNotFound)
	})
}

func TestStore_RemoveTitleFromGroup_CascadesSeasons(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	created, err := s.CreateGroup(ctx, newTestGroup(t, "cascade", owner))
	require.NoError(t, err)
	titleId := "tt-" + uuid.NewString()
	require.NoError(t, s.AddNewGroupTitle(ctx, created.Id, titleId))
	_, err = s.UpdateGroupTitleWatchedForTVSeries(ctx, created.Id, titleId, boolPtr(true), nil, 1, owner)
	require.NoError(t, err)

	require.NoError(t, s.RemoveTitleFromGroup(ctx, created.Id, titleId, owner))

	got, err := s.GetGroupById(ctx, created.Id, owner)
	require.NoError(t, err)
	require.NotContains(t, got.Titles, titleId)

	var seasonCount int
	err = s.pool.QueryRow(ctx,
		`SELECT count(*) FROM group_title_seasons WHERE group_id = $1 AND title_id = $2`,
		created.Id, titleId).Scan(&seasonCount)
	require.NoError(t, err)
	require.Zero(t, seasonCount, "group_title_seasons must cascade-delete with their parent group_title")

	t.Run("non-member guard", func(t *testing.T) {
		err := s.RemoveTitleFromGroup(ctx, created.Id, titleId, "outsider")
		require.ErrorIs(t, err, store.ErrRecordNotFound)
	})
}

func TestStore_UpdateGroupInfo(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	created, err := s.CreateGroup(ctx, newTestGroup(t, "old name", owner))
	require.NoError(t, err)

	require.NoError(t, s.UpdateGroupInfo(ctx, created.Id, "new name", "a description"))

	got, err := s.GetGroupById(ctx, created.Id, owner)
	require.NoError(t, err)
	require.Equal(t, "new name", got.Name)
	require.Equal(t, "a description", got.Description)

	t.Run("missing group is not found", func(t *testing.T) {
		err := s.UpdateGroupInfo(ctx, "no-such-group", "x", "y")
		require.ErrorIs(t, err, store.ErrRecordNotFound)
	})
}

func TestStore_CreateGroup_DuplicateActiveName(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	first, err := s.CreateGroup(ctx, newTestGroup(t, "dupe", owner))
	require.NoError(t, err)

	// Same owner + same name while the first is active => duplicate.
	_, err = s.CreateGroup(ctx, newTestGroup(t, "dupe", owner))
	require.ErrorIs(t, err, store.ErrDuplicatedRecord)

	// UpdateGroupInfo into a taken active name is also a duplicate.
	other, err := s.CreateGroup(ctx, newTestGroup(t, "other", owner))
	require.NoError(t, err)
	err = s.UpdateGroupInfo(ctx, other.Id, "dupe", "")
	require.ErrorIs(t, err, store.ErrDuplicatedRecord)

	// After soft-deleting the first, the name is reusable (partial index only
	// covers non-deleted rows).
	require.NoError(t, s.SoftDeleteGroup(ctx, first.Id))
	reused, err := s.CreateGroup(ctx, newTestGroup(t, "dupe", owner))
	require.NoError(t, err)
	require.NotEmpty(t, reused.Id)
}

func TestStore_RemoveUserFromGroup(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	member := addTestUser(t, s)
	created, err := s.CreateGroup(ctx, newTestGroup(t, "leavers", owner))
	require.NoError(t, err)
	require.NoError(t, s.AddUserToGroup(ctx, created.Id, owner, member))

	require.NoError(t, s.RemoveUserFromGroup(ctx, created.Id, member))

	got, err := s.GetGroupById(ctx, created.Id, owner)
	require.NoError(t, err)
	require.NotContains(t, got.Users, member)
	require.Contains(t, got.Users, owner)

	// The removed member can no longer read the group.
	_, err = s.GetGroupById(ctx, created.Id, member)
	require.ErrorIs(t, err, store.ErrRecordNotFound)

	t.Run("missing/deleted group is not found", func(t *testing.T) {
		require.NoError(t, s.SoftDeleteGroup(ctx, created.Id))
		err := s.RemoveUserFromGroup(ctx, created.Id, owner)
		require.ErrorIs(t, err, store.ErrRecordNotFound)
	})
}

func TestStore_GroupExists(t *testing.T) {
	resetDB(t)
	s := newTestStore(t)
	ctx := context.Background()

	owner := addTestUser(t, s)
	created, err := s.CreateGroup(ctx, newTestGroup(t, "exists", owner))
	require.NoError(t, err)

	ok, err := s.GroupExists(ctx, created.Id, owner)
	require.NoError(t, err)
	require.True(t, ok)

	ok, err = s.GroupExists(ctx, created.Id, "outsider")
	require.NoError(t, err)
	require.False(t, ok, "non-members must not see the group as existing")

	require.NoError(t, s.SoftDeleteGroup(ctx, created.Id))
	ok, err = s.GroupExists(ctx, created.Id, owner)
	require.NoError(t, err)
	require.False(t, ok, "a soft-deleted group must not exist")
}
